Parkminsu Chapter4 Exercise code
NHN-Default-Project/DefaultProject pull request #11
Opened 2023-09-18 07:59 UTC by minsu11

2023-09-18 08:02 UTC, NANNDA3463 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_1/Exercise4_1.java
> +                    upperCheck = true;
upperCheck가 false가 되는 구간이 없어 첫 단어의 첫글자만 대문자로 변하고, 두번째 단어에서부터는 되지 않는 것 같아요.

2023-09-18 08:03 UTC, NANNDA3463 approved these changes

2023-09-18 08:07 UTC, NANNDA3463 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_2/Exercise4_2.java
> +            return num - 87;
이것도 아래 '0'처럼 char 값으로 넣으면 어떨까요?

2023-09-18 10:13 UTC, hyeonjaez reviewed
우와 객체지향적으로 하려고 하는게 보여서 좋은거 같아요!! 
진짜 잘하셨네요

2023-09-18 10:13 UTC, hyeonjaez commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_1/Exercise4_1.java
> +    public StringBuilder pringCapialized(String str) {
pring이 어떤 의미를 가지고 있나요? 아 혹시 print 오타이면 수정 부탁드립니다!!

2023-09-18 10:13 UTC, hyeonjaez commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_1/Exercise4_1.java
> +                if (!upperCheck) {
따로 boolean 형태로 check하는 메서드를 만들어서 분리 해주는건 어떨까요?

2023-09-18 10:13 UTC, hyeonjaez commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_2/Exercise4_2.java
> +            value = value * 16 + hexValue(str.charAt(i));
원하는 결과값이 안나오네요 아마도 여기 구문이 잘못되어서 그런거 같아요!! 다시 코드 짜야겠네요ㅎㅎ

2023-09-18 10:13 UTC, hyeonjaez commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_3/Dice.java
> +    public void setDiceEye(int diceEye) {
setter 말고 생성자로 값을 설정해주는 방식은 어떨까요??

2023-09-18 10:13 UTC, hyeonjaez commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_3/DiceCollection.java
> +    public void averageTotalDice() {
메서드 이름 첫 단어는 무조건 동사로 !!

2023-09-18 10:13 UTC, hyeonjaez commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_3/Exercise4_3.java
> +            System.out.printf("굴린 횟수: %d\n주사위1 눈: %d\n주사위2 눈: %d\n\n",
세개로 나눠서 쓰는게 어떨까요??

2023-09-18 10:13 UTC, hyeonjaez commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_5/ArrayAverage.java
> +}
챕터 5번 모두다 람다식으로 수정 해주세요!!

2023-09-18 12:29 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_1/Exercise4_1.java
> +    public StringBuilder pringCapialized(String str) {
좋은 지적 감사합니다~~

2023-09-19 07:08 UTC, 20203174 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_2/Exercise4_2.java
> +    public static boolean stringCheck(String str) {
문제에서 요구한 isLetter()메소드를 사용하셔도 좋을 것 같습니다!@

2023-09-19 07:29 UTC, 20203174 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_7/Exercise4_7.java
> +            changeToGreen(currentRow, currentColumn);
메소드의 역할에 맞는 이름으로 수정해주면 더욱 보기에 좋을 것 같습니다!

2023-09-19 09:10 UTC, hyeonjaez reviewed
comment 달았습니다

2023-09-19 09:10 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_1/PairOfDice.java
> +    private int snakeSum;
이런 값들은 상수로 지정해주는게 좋을거 같아요!

2023-09-19 09:10 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_1/PairOfDice.java
> +        snakeSum = 2;
확장성을 생각하면 객체를 생성할때 이렇게 값을 정해지는건 좋지 않을것 같아요

2023-09-19 09:10 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_2/Exercise5_2.java
> +        System.out.println(statCalc.getCount());
StatCalc 안에 toString을 오버라이딩 하고 여기서 호출하면 깔끔하게 될거 같아요

2023-09-19 09:10 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_3/Exercise5_3.java
> +    private static int ARANGE = 10000;
final 키워드가 필요합니다

2023-09-19 09:10 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_3/Exercise5_3.java
> +    private static final int endRDiceSumnange = 12;
상수는 모든 문자 대문자로 그리고 한단어씩 _로 끊어서 작성해야합니다 
예를 들어 위에 있는 상수 네이밍을 END_DICE_SUM_RANGE 가 됩니다ㅎ

2023-09-19 09:10 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_3/Exercise5_3.java
> +    private static final int arraySize = endRDiceSumnange - beginDiceSumRange + 1;
이건 ARRAY_SIZE 입니다ㅎ

2023-09-19 09:10 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_3/Exercise5_3.java
> +            System.out.println("평균 : " + avageCnt(statCalc[i]));
뭐에 대한 평균인지 명확하게 작성 해주세요

2023-09-19 09:10 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_3/Exercise5_3.java
> +    public static double avageCnt(StatCalc statCalc) {
메서드 이름은 첫단어는 동사로 그러면 위에 있는건 countAverage가 됩니다

2023-09-19 09:10 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_4/Exercise5_4.java
> +    private static final int MAXCARDCOUNT = 6;
상수 이름은 단어마다 "_ "가 있어야 합니다

2023-09-19 09:10 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_4/Exercise5_4.java
> +        System.out.println(blackjackHand.getBlackjackValue());
이거 전에 모든 카드도 print 해달라는 요청사항이 있었습니다
문제 다시 확인해 주세요

2023-09-19 09:10 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_4/Exercise5_4.java
> +        Scanner scanner = new Scanner(System.in);
scanner.close()를 하시거나 try-catch 를 사용해주세요

2023-09-19 09:10 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_6/Exercise5_6.java
> +    private static final int questionCount = 10;
상수 네이밍 규칙을 적용해주세요

2023-09-19 09:10 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_7/Exercise5_7.java
> +    private static final int range = 10;
상수는 대문자로 해주세요

2023-09-19 09:10 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_7/Exercise5_7.java
> +        Scanner scanner = new Scanner(System.in);
scanner.close() 해주세요

2023-09-19 11:00 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_2/Exercise4_2.java
> +    public static boolean stringCheck(String str) {
메소드 이름이 stringCheck여서 오해가 생긴 것 같습니다! 해당 메소드가 16진수의 데이터 값인지 아닌지 판별하는 메소드여서 isLetter()메소드는 사용안하는 쪽으로 했고, 메소드 이름만 checkHexValue로 변경했습니다!

2023-09-19 11:07 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_3/DiceCollection.java
> +    public void averageTotalDice() {
수정했습니다!

2023-09-19 11:08 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_3/Exercise4_3.java
> +            System.out.printf("굴린 횟수: %d\n주사위1 눈: %d\n주사위2 눈: %d\n\n",
수정했습니다!

2023-09-19 11:12 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_3/Dice.java
> +    public void setDiceEye(int diceEye) {
생성자에 해주게 되면 DiceCollection에서 roll을 하게 됐을 때 계속 dice의 객체를 만들어주기 때문에 메모리에 비효율적으로 저장이 될 거 같아서 setDiceEye 메소드에서 값을 받아오는 방식으로 했습니다!

2023-09-19 11:13 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_5/ArrayAverage.java
> +}
람다식으로 되어있습니다!

2023-09-19 11:19 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_7/Exercise4_7.java
> +            changeToGreen(currentRow, currentColumn);
수정했습니다!

2023-09-19 11:21 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_2/Exercise4_2.java
> +            return num - 87;
10을 만들기위해서 소문자 a 97에서 뺀 숫자를 넣은 거여서 87이 맞을거 같아요!!

2023-09-19 11:21 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_1/Exercise4_1.java
> +                    upperCheck = true;
수정했습니다!

2023-09-19 11:24 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_1/PairOfDice.java
> +    private int snakeSum;
수정했습니다!

2023-09-19 11:25 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_1/PairOfDice.java
> +        snakeSum = 2;
수정했습니다!!

2023-09-19 11:31 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_2/Exercise5_2.java
> +        System.out.println(statCalc.getCount());
수정했습니다!

2023-09-19 12:28 UTC, NANNDA3463 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_5/Exercise4_5.java
> +    public static final ArrayProcessor ARRAYMIN = array -> DoubleStream.of(array).min().getAsDouble();
.getAsDouble 메서드는 Optional Method로, 변수에  null이 들어오는 것을 막기 위해 만들어졌습니다. 값이 있으면 값을 리턴하지만, 값이 없을경우 (null)일경우 isPresent를 반환하는데, .getAsDouble 뒤에 .orElse()를 추가하면, null일 경우의 값을 지정해줄 수 있습니다.

2023-09-19 12:30 UTC, NANNDA3463 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_8/QuizShow.java
> +            user.writeAnswer(i, scanner.nextInt());
scanner로 읽어들인 값이 숫자가 아닐 때가 고려가 되지 않은 것 같습니다. try catch resource를 쓰면 어떨까요

2023-09-19 12:32 UTC, NANNDA3463 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_8/Quiz.java
> +    private Map<Integer, Integer> answerList;
HashMap의 key값으로 index(정확히는 index + 1)만 들어가던데 list나 array를 쓰지 않은 이유가 있을까요?

2023-09-19 12:34 UTC, NANNDA3463 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_8/Quiz.java
> +    public static class Question {
static class가 아닌 Quiz 안에 static Class가 있는게 조금 의아합니다. 따로 분리해도 괜찮지 않을까요?

2023-09-19 12:35 UTC, NANNDA3463 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_8/QuizShow.java
> +    private QuizUser user;
QuizUser라는 클래스의 의미가 결국 HashMap밖에 없으니 이는 별도의 클래스보다 HashMap 자료형으로 쓰는 것도 괜찮을 것 같아요.

2023-09-19 12:43 UTC, NANNDA3463 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_1/PairOfDice.java
> +        this.snakeSum = snakeSum;
주사위의 합계이니, diceSum은 어떨까요?

2023-09-19 12:48 UTC, NANNDA3463 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_4/Exercise5_4.java
> +        if (num < MIN_CARD_COUNT && num > MAX_CARD_COUNT) {
범위가 제대로 적용이 되지 않았습니다. || 로 바꿔주세요

2023-09-19 12:51 UTC, NANNDA3463 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_5/Exercise5_5.java
> +            System.out.print("카드 장 수를 고르세요");
문제에서는 2장만 받기로 했습니다.

2023-09-19 12:52 UTC, NANNDA3463 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_5/Game.java
> +        if (cardNum < this.cardFirstRange && cardNum > this.cardEndRange) {
범위가 잘못되었습니다! ||로 바꿔주세요

2023-09-19 12:52 UTC, NANNDA3463 requested changes
P민수의 리뷰를 진행중입니다.

2023-09-20 02:04 UTC, 20203174 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_3/Exercise5_3.java
> +public class Exercise5_3 {
2~12까지 각각의 합계에 대한 통계값이 아닌 10000번 돌린 횟수 중에서의 평균값이 출력되는 것 같습니다... 확인 부탁드립니다!

2023-09-20 02:07 UTC, 20203174 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_4/Exercise5_4.java
> +    public static void main(String[] args) {
사용자가 입력해야 하는 값을 먼저 출력해줘도 좋을 것 같습니다 그리고 어떤 카드를 뽑았는지도 화면에 보여주면 좋을 것 같아요 !!

2023-09-20 02:18 UTC, 20203174 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_5/BlackjackCondition.java
> +        return userOrDealer.getBlackjackValue() <= 21;
버스트는 카드 총합이 21을 넘는 경우입니다! 반대로 된 것 같네용

2023-09-20 02:19 UTC, 20203174 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_5/Game.java
> +                if (deckCondition(this.dealer)) { // 블랙잭 승리 조건 1
유저가 블랙잭인지 확인하는 경우가 빠진 것 같습니당

2023-09-20 02:30 UTC, 20203174 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_5/BlackjackCondition.java
> +            return user.getBlackjackValue() < dealer.getBlackjackValue();
딜러와 사용자가 값이 같은 경우도 추가해주면 좋을 것 같습니당 ( <= )

2023-09-20 03:30 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_8/Quiz.java
> +    public static class Question {
quiz안에 question이라는 요소가 포함이 된다라고 생각했고, 따로 분리 하지 않은 이유는 question은 값을 저장하고 get으로 값을 얻기만하는 class여서 따로 분리하지 않고 Quiz안에 포함 시켰습니다

2023-09-20 03:40 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_8/Quiz.java
> +    private Map<Integer, Integer> answerList;
지금 10문제라고 범위가 한정되어 있지만, 추후의 문제의 갯수가 10문제가 아닌 다른 범위가 지정되면 배열은 코드를 수정을 해줘야하는 불편함이 생긴다고 생각을 해서 사이즈를 가변적으로 할 수 있고 Integer 타입 2개를 map으로 묶으면 추후에 코드 수정을 할  필요가 없을 거라고 생각을 해서 Map으로 했습니다!

2023-09-20 03:51 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_4/Exercise5_4.java
> +    public static void main(String[] args) {
출력값으로 나오게 수정 했습니다!

2023-09-20 03:59 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_5/Game.java
> +                if (deckCondition(this.dealer)) { // 블랙잭 승리 조건 1
유저는 블랙잭이고 딜러는 16이하인 경우 딜러가 카드를 받으면서 블랙잭이 될 수도 있는 경우가 생길 수 도 있는데 이 부분에 유저가 이기는 조건문을 쓰게 된다면 이러한 경우를 지나치고 유저의 승리로 표시가 될 수도 있다고 생각을 해서 넣지 않았습니다!!

2023-09-20 03:59 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_5/Game.java
> +        if (cardNum < this.cardFirstRange && cardNum > this.cardEndRange) {
|| 연산자로 수정했습니다!

2023-09-20 04:00 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_5/BlackjackCondition.java
> +        return userOrDealer.getBlackjackValue() <= 21;
해당 메소드의 이름을 notBustCondition으로 변경했습니다!!

2023-09-20 04:10 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_5/Exercise5_5.java
> +            System.out.print("카드 장 수를 고르세요");
해당 구문은 삭제해서 수정했습니다!!

2023-09-20 04:10 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_5/BlackjackCondition.java
> +            return user.getBlackjackValue() < dealer.getBlackjackValue();
해당 조건문을 삭제해서 수정했습니다!!

2023-09-20 04:14 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_7/Exercise5_7.java
> +    private static final int range = 10;
대문자로 수정했습니다!

2023-09-20 04:14 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_7/Exercise5_7.java
> +        Scanner scanner = new Scanner(System.in);
수정했습니다!!

2023-09-20 05:09 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_3/Exercise5_3.java
> +            System.out.println("평균 : " + avageCnt(statCalc[i]));
해당 문제가 요구한 대로 수정했습니다!

2023-09-20 05:10 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_3/Exercise5_3.java
> +public class Exercise5_3 {
10000번 돌린 횟수 중에서의 평균값으로 출력이 되게 수정했습니다!

2023-09-20 05:41 UTC, NANNDA3463 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_4/Exercise5_4.java
> +        } catch (IllegalArgumentException e) {
InputMismatchException 도 처리 해주면 좋을 것 같습니다!
해당 Exception은 타입이 맞지 않은 입력을 받았을 때 나타납니다.

2023-09-20 05:44 UTC, NANNDA3463 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_8/Quiz.java
> +    public static class Question {
퀴즈 안의 요소가 같은 것이라면 포함이 되는 것이라면 static이 아니어도 괜찮을 것 같아요
static으로 해두면 Quiz는 new Quiz instance를 생성해야 사용이 가능한데, Question은 static이기 때문에 new Quiz를 하지 않아도, 컴파일러 실행 단계에서 어딘가에 할당이 되어있을 것 같아요.

2023-09-20 05:48 UTC, NANNDA3463 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_4/Exercise5_4.java
> +        }
문제에 사용자가 계속하기를 원하는 동안 이 작업을 반복하라는 언급이 있었습니다. 반영하는 것도 괜찮을 것 같아요

2023-09-20 05:49 UTC, NANNDA3463 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_5/Exercise5_5.java
> +            if (!start.equals("YES")) {
입력값 'no'에 대한 처리가 없습니다.

2023-09-20 05:53 UTC, NANNDA3463 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_5/Game.java
> +                showCard(this.user);
97번 라인 코드에 showCard(this.user)를 출력했어서 이 부분을 생략해도 괜찮을 것 같아요

2023-09-20 06:09 UTC, NANNDA3463 reviewed
0920 Pminsoo 리뷰하였습니다.

2023-09-20 06:09 UTC, NANNDA3463 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_5/BlackjackCondition.java
> +public class BlackjackCondition {
해당 클래스의 메소드들을 static으로 쓰는 것보다 어차피 Game이 시작될 때 사용해야하는 것들이라면 Game 내에 BlackjackCondition을 instance로 생성하여 사용하는 편이 더 좋을 것 같아요.

2023-09-20 06:09 UTC, NANNDA3463 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_5/Game.java
> +        }
유저의 카드 정보와 함께, 패 합계의 점수도 출력해주면 좋을 것 같습니다.

2023-09-20 06:09 UTC, NANNDA3463 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_7/SubstractQuestion.java
> +    public SubstractQuestion() {
문제에 답이 음수가 되면 안된다는 조건이 있어 이를 추가해주면 좋을 것 같습니다.

2023-09-20 06:09 UTC, NANNDA3463 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_7/Exercise5_7.java
> +            answer[i] = scanner.nextInt();
InputMismatchException 과같은 Exception들을 처리해주면 좋을 것 같습니다.

2023-09-20 06:59 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_4/Exercise5_4.java
> +        } catch (IllegalArgumentException e) {
추가해서 수정했습니다

2023-09-20 07:19 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_4/Exercise5_4.java
> +        }
수정했습니다!

2023-09-20 07:19 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_4/Exercise5_4.java
> +        Scanner scanner = new Scanner(System.in);
scanner.close() 추가해서 수정했습니다!

2023-09-20 07:25 UTC, prospro1 reviewed
submit test 입니다. 4_1 과 4_2 일부 코멘트가 날아갔는지를 확인해보겠습니다!

2023-09-20 07:25 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_1/Exercise4_1.java
> +            System.out.println(main.printCapialized(scanner.nextLine()));
printCapialized() 메서드를 static으로 안하시고 인스턴스 메서드로 하신 이유가 따로 있을까요? Exercise4_1 클래스 인스턴스를 따로 생성하신 이유가 궁금합니다!!

2023-09-20 07:25 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_1/Exercise4_1.java
> +                if (!upperCheck || idx == str.indexOf(" ")) {
위의 if 문에서 알파벳 문자인지를 체크를 했기 때문에, 여기에는 공백이 절대 들어올 수 없을 것 같습니다!! 따라서 idx == str.indexOf(" ") 이 부분을 삭제해주셔도 무방할 것 같습니다 :)

2023-09-20 07:25 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_2/Exercise4_2.java
> +            throw new IllegalArgumentException("데이터를 잘못 입력하셨습니다");
사실 cnt가 str 길이와 같지 않은 모든 경우가, 데이터를 잘못 입력한 값일 것 같습니다! 그리고 cnt 가 3보다 작다는 조건보다는 cnt < str.length() 가 더 맞을 것 같습니다! 사실 이렇게 되면 else 는 왜 필요한지 궁금해집니다...!

2023-09-20 07:25 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_2/Exercise4_2.java
> +            throw new IllegalArgumentException("데이터를 잘못 입력하셨습니다");
return true가 아닐 때는 else if 든 else 든 모두 return false를 반환해주어야 하는 게 아닌가 싶은데, throw를 던져서 return false를 못해주는 경우가 문제가 되지 않을까 조심스럽게 생각해봅니다.

2023-09-20 07:25 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_2/Exercise4_2.java
> +            return num - 87;
여기서 char이 들어올 때 무조건 소문자로만 들어와야 값이 변환되는 게 아쉬운 것 같습니다...! 아래의 calculator에서 toLowerCase() 활용하셔서 문제는 없지만 그래도 좀 더 사용성을 높이려면 hexValue() 메서드 자체에 대문자든 소문자든 숫자든 들어왔을 때 다 동작하게 만드는 게 더 좋지 않을까요~?

2023-09-20 07:25 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_2/Exercise4_2.java
> +            return -1;
위의 checkHexValue() 메서드에서 cnt < 3 일 때는, 즉, else if 일 때 throw 를 해버렸기 때문에 여기 return -1 부분이 들어올 수가 없습니다. 그런데 애초에 문제에서 -1을 리턴하라고 만들라고 했던 곳은 hexValue() 메서드 안이었고, 이런 리턴값을 받는 이유 자체가 exception을 throw 하기 위해서 였기 때문에, calculator에서 -1을 리턴하는 게 조금 의도와 맞지 않을 수도 있을 것 같습니다...!

2023-09-20 07:25 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_2/Exercise4_2.java
> +            return -1;
그리고 이렇게 하실 거라면 오히려 main 문에서 calculator() 메서드 결과값을 저장하는 변수를 생성해서 값이 -1이라면 잘못된 값이 들어왔다는 exception을 던져줘야 하지 않나 싶습니다!

2023-09-20 07:27 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_1/Exercise4_1.java
> +                if (!upperCheck || idx == str.indexOf(" ")) {
수정했습니다!

2023-09-20 07:29 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_2/Exercise4_2.java
> +    public static int hexValue(char num) {
들어오는 파라미터 자체가 이미 hexValue인 것만 들어오는 것이 아쉽습니다...!

2023-09-20 07:32 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_2/Exercise4_2.java
> +
문제의 조건에서 switch 문을 활용해보라고 제시하였으니, 한 번 switch 문으로 작성해보시는 것도 좋을 것 같습니다! 물론 지금 이 상태로도 수정하고 싶으신 부분 수정해보시는 것도 공부에 도움이 될 것 같습니다 ㅎㅎ

2023-09-20 07:57 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_3/DiceCollection.java
> +        if (this.getFirstDice().getDiceEye() + this.getSecondDice().getDiceEye() > 12) {
이 메서드가 사실상 의미가 없는 것 같습니다...! 이미 diceEye를 Math.random() 사용해서 값을 지정할 때부터 1부터 6까지의 값이 나올 수밖에 없게끔 만들어놓으셔서, 이 조건문에 들어올 수가 없을 것 같습니다.

2023-09-20 07:58 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_3/DiceCollection.java
> +        if (this.getFirstDice().getDiceEye() + this.getSecondDice().getDiceEye() > 12) {
사실 이 메서드가 의미가 있어지는 것은 주사위 합의 목표 값 totalSum을 사용자로부터 입력을 받을 때인 것 같습니다. 사용자가 입력한 값이 도달할 수 있는 값이 아닐 때, 애초에 달성할 수 없는 합 목표 값이라고 알려주는 용도로 사용하시면 더 좋을 것 같습니다!!

2023-09-20 07:58 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_3/DiceCollection.java
> +        if (this.getFirstDice().getDiceEye() + this.getSecondDice().getDiceEye() > 12) {
그렇게 되면 파라미터로 totalSum을 받아서, totalSum 자체가 12 초과인지, 2 미만인지를 체크하는 건 어떨까요~?

2023-09-20 08:10 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_3/DiceCollection.java
> +            for (int i = this.totalBeginRange; i <= totalEndRange; i++) {
이중 for 문을 사용하실 때, 두 for문의 위치가 바뀐 것 같습니다...! 제가 이해한 바로는, 합이 가능한 범위의 가장 작은 값(여기서는 2) 부터 합이 가능한 범위의 가장 큰 값(여기서는 12) 까지를 돌면서, 각각의 합을 만들어야하는 값이 정해졌을 때, 총 endDiceRolled, 즉 실험해볼 횟수(여기서는 10_000 번)을 돌려보고, 그 10000번에 대한 평균과 표준편차, 그리고 max 값을 보고 실험에서 의미있는 결과값을 얻어내는 것이라고 생각합니다...! 따라서 두 줄을 바꿔주시는 게 어떨까 싶습니다..!

2023-09-20 08:14 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_3/DiceCollection.java
> +    public void findAverageTotalDice() {
혹시 위의 코멘트처럼 변경하신다면 여기도 beginRange 부터 endRange까지의 범위가 아니라, 범위 설정이 endDicefRolled 번만큼 돌도록 바꾸셔야할 것 같습니다...! 참고 부탁드립니다 :)

2023-09-20 08:28 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_5/Exercise4_5.java
> +    public static final ArrayProcessor ARRAYMIN = array -> DoubleStream.of(array).min().getAsDouble();
저도 이렇게 작성해서 orElse() 를 추가해야겠네요! 좋은 정보 감사합니다!

2023-09-20 08:42 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_6/Exercise4_6.java
> +        int blue = 0;
사실 여기서 red와 blue를 0으로 설정해버린다는 것은 처음에 모든 모자이크의 색상이 black이기에 가능한 거라고 생각합니다! 그래서 메서드 명도 changeToGreen 이라고 하신 것 같아요! 그런데 문제에서 그린 색상만 조금씩 25씩 추가해주는 메서드라고 했기 때문에, 사용성을 높여주려면 수정이 필요해보입니다..!

2023-09-20 08:42 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_6/Exercise4_6.java
> +        int blue = 0;
물론 아예 초록색으로만 보이게 만들고 싶으시다면 이 메서드 명이 의도와 걸맞습니다. 다만, 지금처럼 블랙 컬러로 시작하는 것이 아니라, 랜덤 컬러로 시작해도 그저 초록 값만 조금 추가해주는 정도로 메서드를 사용할 수 있게 만들려면, addLittleGreen 처럼 메서드 명을 변경해주시고, 해당 행과 열의 기존의 red와 blue 값은 그대로 받아오고, green 값만 기존 값 받아온 거에 25를 더해주는 식으로 만들어주시면 어떨까 생각해봅니다 :)

2023-09-20 08:45 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_7/Exercise4_7.java
> +        currentColumn = COLUMNS / 2;
문제에서 모자이크의 직사각형 중 하나를 무작위로 선택하고 그 이후 인접한 것을 택하라 되어있으므로, 여기서 currentRow 와 currentColumn 을 중점으로 설정하지 마시고, 랜덤으로 받을 수 있게 하는 것이 좋을 것 같습니다 :)

2023-09-20 08:59 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_8/QuizShow.java
> +                System.out.printf("틀렸습니다. \n%d문제의 사용자 답: %d\n 정답 : %d\n", i,
틑렸을 때도 몇 번 문제 틀렸는지 알려주시면 좋을 것 같아요!

2023-09-20 09:03 UTC, prospro1 reviewed
yunhwa reviewed up to all the Chapter4 exercises!

2023-09-20 09:07 UTC, prospro1 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_1/Exercise5_1.java
> +        System.out.printf("%d %d : %d\n", pairOfDice.getDie1(), pairOfDice.getDie2(), pairOfDice.getRollDiceCount());
출력문을 봤을 때, 이게 어떤 동작을 하는 프로그램인지 잘 모르겠습니다...! 출력 형식을 조금 더 프로그램을 이해하기 쉽게 보완해주시면 너무 좋을 것 같아요!!

2023-09-20 09:09 UTC, prospro1 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_1/PairOfDice.java
> +    private int rollDiceCount;
주사위 한 쌍이라는 개념에 몇 번을 돌렸는지가 필드로 포함되는 것보단 돌리는 작업을 관리하는 곳에서 이걸 필드로 선언하는 게 더 의미가 맞지 않을까 조심스럽게 추천해봅니다...!

2023-09-20 09:19 UTC, prospro1 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_1/PairOfDice.java
> +    public PairOfDice(int diceSum) {
한 쌍의 주사위를 생성할 때 왜 두 주사위의 눈의 합으로 만들고 싶은 합계 값을 파라미터로 입력받아야 하는지 잘 모르겠습니다...! 그리고 만약 이렇게 하실 거라면 변수명을 주사위의 합이 아니라 주사위 눈의 합이라고 변수명을 설정해주는 것이 좀 더 의미가 명확해지지 않을까 조심스럽게 생각해봅니다...!

2023-09-20 09:21 UTC, prospro1 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_2/StatCalc.java
> +            throw new IllegalArgumentException("종료하였습니다.");
이렇게 되면 무조건 비정상 종료만 될 것 같아서 에러처럼 느껴질 것 같아 조금 아쉬운 것 같습니다...! 정상 종료가 되도록 해주시면 더 좋지 않을까요~?

2023-09-20 09:22 UTC, prospro1 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_2/StatCalc.java
> +}  // end class StatCalc
toString() 으로 해주신 거 너무 좋은 것 같습니다!!

2023-09-20 09:39 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_3/Exercise5_3.java
> +    private static final int BEGIN_DiceSum_Range = 2;
상수 이름은 대문자로 부탁드립니다ㅎ

2023-09-20 09:39 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_3/Exercise5_3.java
> +                    System.out.println("break");
처음에 break 란 문장이 여러번 출력이 됩니다 아마 이 문장때문에 그런거 같은데 수정해주세요

2023-09-20 09:40 UTC, prospro1 reviewed
yunhwa reviewed up to Chapter5 - Exercise5_2

2023-09-20 10:42 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_1/Exercise4_1.java
> +            System.out.println(main.printCapialized(scanner.nextLine()));
문제 번역할 때 main루틴을 사용하여 서브루틴을 테스트 합니다 라는 문장을 main.메소드로 호출하라는 걸로 이해해서 이렇게 했습니다 static으로 수정 하겠습니다!

2023-09-20 10:51 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_2/Exercise4_2.java
> +            return num - 87;
대문자 소문자 둘 다 들어오게 만들기 위해서 밑에서 들어오는 String의 값을 toLowerCase()를 활용했습니다!

2023-09-20 10:53 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_2/Exercise4_2.java
> +            throw new IllegalArgumentException("데이터를 잘못 입력하셨습니다");
문제에서 16진수 숫자 중 하나가 아닌 경우를 -1로 하라는 조건이 있어서 하나만 틀렸을 때 false로 나오게 하고 한 개이상이 틀렸을 경우에는 throw를 던져서 입력한 값이 잘못 되었다고 알려주기 위해서 해당 조건문을 작성했습니다!

2023-09-20 10:53 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_2/Exercise4_2.java
> +            throw new IllegalArgumentException("데이터를 잘못 입력하셨습니다");
말씀해준 범위는 문자열의 길이에서 -1를 한 값으로 변경했습니다!

2023-09-20 10:55 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_2/Exercise4_2.java
> +            return -1;
입력받은 16진수가 한 자리만 잘못 되었을 때 -1 리턴하라는 걸로 이해해서 한자리만 틀렸을 때 -1를 반환하게 만들었습니다!

2023-09-20 11:01 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_3/DiceCollection.java
> +            for (int i = this.totalBeginRange; i <= totalEndRange; i++) {
문제 이해를 잘못한 것같습니다 수정하겠습니다!

2023-09-20 11:02 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_5/Exercise4_5.java
> +    public static final ArrayProcessor ARRAYMIN = array -> DoubleStream.of(array).min().getAsDouble();
수정하겠습니다!

2023-09-20 11:04 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_6/Exercise4_6.java
> +        int blue = 0;
현재 코드에서는 처음 찍을 때 랜덤컬러로 색칠이 됩니다! 랜덤 컬러로 찍히는 부분은 제가 문제를 제대로 이해하지 않아서 생긴 오류입니다! 처음 색칠 할 때 블랙으로 수정하겠습니다!

2023-09-20 11:06 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_6/Exercise4_6.java
> +        int blue = 0;
문제에서 초록색으로 색칠을 하게 만들라고해서 red와 blue의 값을 0으로 해줬습니다! 윤화씨 말대로 그것도 좋은 방법인거 같습니다!

2023-09-20 11:07 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_8/QuizShow.java
> +            user.writeAnswer(i, scanner.nextInt());
넵 수정하겠습니다!

2023-09-20 11:08 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_8/QuizShow.java
> +                System.out.printf("틀렸습니다. \n%d문제의 사용자 답: %d\n 정답 : %d\n", i,
틀렸을 때도 몇번이 틀렸는지 출력이 됩니다!

2023-09-20 11:21 UTC, prospro1 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_5/BlackjackCondition.java
> +    public static boolean dealerkDeckCheck(BlackjackHand dealer) { // 딜러가 카드를 받을지 안받을지의 조건
이 메서드 이름 중간에 k가 들어가는 이유가 궁금합니다...! 딜러의 덱이라는 것을 의미하는 s를 오타를 내신 것인지 아니면 다른 이유가 있는지 알려주시면 감사하겠습니다 :)

2023-09-20 11:22 UTC, prospro1 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_5/BlackjackCondition.java
> +public class BlackjackCondition {
저도 동의합니다!

2023-09-20 11:25 UTC, prospro1 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_5/BlackjackCondition.java
> +    public static boolean hitOrStandard(String callSign, String compareStr) {
메서드 명에서 'Standard' 보다는 'Stand' 로 표기하시는 게 더 좋을 것 같아요!!

2023-09-20 11:35 UTC, prospro1 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_5/Game.java
> +                showCard(this.user);
저도 동의합니다!

2023-09-20 11:37 UTC, prospro1 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_5/CardAction.java
> +            System.out.printf("%d ", blackjackHand.getCard(i).getValue());
Game 클래스의 gameFirstStep() 메서드에서 "딜러의 패: ", "유저의 패:" 이렇게 출력해주신 것 처럼 여기서도 동일하게 처리해주시면 보다 게임을 진행하기 편할 것 같습니다!

2023-09-20 11:38 UTC, prospro1 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_5/CardAction.java
> +            System.out.printf("%d ", blackjackHand.getCard(i).getValue());
그리고 이 메서드를 위에서 말씀드린, Game 의 gameFirstStep() 메서드에서도 call 해서 사용해주시면 좋지 않을까 생각해봅니다 :)

2023-09-20 11:53 UTC, prospro1 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_7/Exercise5_7.java
> +        substract = createArrayIntQuestion(substract);
변수명이 아쉽습니다! IntQuestion[] 이고, createArrayIntQuestion() 메서드를 통해서 들어가는 값이 SubstractQuestion 만 있는 건 아니고, AdditionQuestion 도 절반 들어가게 해두셨으니, 그에 맞게 변수명을 변경해주심이 어떠신지요 :)

2023-09-20 11:55 UTC, prospro1 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_7/Exercise5_7.java
> +    public static IntQuestion[] createArrayIntQuestion(IntQuestion[] intQuestions) {
그리고 이 메서드에서 abstract class로 생성된 질문도 추가하면 더 좋지 않을까 싶습니다! 문제에서 제안하기로, 익명 클래스로 생성된 다음 질문을 포함하여 수학 이외의 몇 가지 질문을 추가할 수도 있다고 하였으므로 한 번 시도해보시는 것도 추천드립니다!

2023-09-20 11:57 UTC, prospro1 reviewed
yunhwa reviewed all the Chapter5 Exercises!

2023-09-20 23:39 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_8/QuizShow.java
> +    private QuizUser user;
유저가 적은 답과 퀴즈쇼의 답은 별도로 존재하는게 더 나은 방향이라고 생각해서 별도의 클래스로 나눠놨습니다

2023-09-20 23:44 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_7/Exercise4_7.java
> +        currentColumn = COLUMNS / 2;
랜덤으로 받을 수 있게 수정했습니다!

2023-09-21 00:26 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_2/Exercise4_2.java
> +    public static int hexValue(char num) {
16진수를 계산하는 메소드이기 때문에 16진수로 된 것만 들어오게 만들었습니다!

2023-09-21 00:52 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/parkminsu/Exercise4_3/DiceCollection.java
> +        if (this.getFirstDice().getDiceEye() + this.getSecondDice().getDiceEye() > 12) {
수정했습니다!

2023-09-21 05:11 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_2/StatCalc.java
> +            throw new IllegalArgumentException("종료하였습니다.");
수정했습니다!

2023-09-21 05:34 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_5/BlackjackCondition.java
> +    public static boolean hitOrStandard(String callSign, String compareStr) {
수정했습니다!

2023-09-21 05:34 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_5/BlackjackCondition.java
> +    public static boolean dealerkDeckCheck(BlackjackHand dealer) { // 딜러가 카드를 받을지 안받을지의 조건
수정했습니다!

2023-09-21 05:37 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_5/Exercise5_5.java
> +            if (!start.equals("YES")) {
수정했습니다

2023-09-21 05:38 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_5/Game.java
> +        }
수정했습니다!

2023-09-21 05:39 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_7/Exercise5_7.java
> +            answer[i] = scanner.nextInt();
수정했습니다!

2023-09-21 05:39 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_7/Exercise5_7.java
> +    public static IntQuestion[] createArrayIntQuestion(IntQuestion[] intQuestions) {
수정했습니다!

2023-09-21 05:40 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/parkminsu/Exercise5_7/Exercise5_7.java
> +        substract = createArrayIntQuestion(substract);
수정했습니다!

2023-09-22 02:09 UTC, hyeonjaez approved these changes
code approve

2023-09-22 02:09 UTC, NANNDA3463 approved these changes

2023-09-22 02:10 UTC, 20203174 approved these changes
code approve

2023-09-22 02:14 UTC, merged