gaeun Chapter7
NHN-Default-Project/DefaultProject pull request #22
Opened 2023-09-27 06:11 UTC by 20203174

2023-09-27 07:32 UTC, hyeonjaez commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise1/Exercise7_1.java
> +        Scanner scanner = new Scanner(System.in);
try-with-resources 적용해주면 좋을거 같아요!!

2023-09-27 07:32 UTC, hyeonjaez commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise3/RandomStringArray.java
> +                .toString();
오 랜덤 문자열 만드는것을 stream사용해서 하셨군요. 보고 배울게요

2023-09-27 07:32 UTC, hyeonjaez commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise3/Exercise7_3.java
> +        System.out.println("Arrays.sort Time is: " + compTime);
시간 재는 메서드 하나 분리해서 구현하는건 어떨까용??

2023-09-27 07:32 UTC, hyeonjaez commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise5/Main.java
> +        Scanner scanner = new Scanner(System.in);
try-with-resources 참고해주세요. 이거 아니면 scanner.close()라도 부탁 드립니다.

2023-09-27 07:32 UTC, hyeonjaez commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise5/Main.java
> +    public static void quickSort(int[] inputArray) {
퀵정렬 쓰셨군요 굿굿

2023-09-27 07:32 UTC, hyeonjaez commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise6/FileRead.java
> +    FileRead(String readPath, String writePath) {
접근제어자를 default로 설정한 이유가 있을까요?

2023-09-27 07:32 UTC, hyeonjaez commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise6/FileRead.java
> +    private List<String> wordList = new ArrayList<>();
인스턴스 변수를 생성자에서 초기화를 하지 않은 이유가 있을까요??

2023-09-27 07:32 UTC, hyeonjaez commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise6/FileRead.java
> +public class FileRead {
코드의 가독성을 높이기 위해 this를 써주는게 어떨까요?

2023-09-27 07:32 UTC, hyeonjaez commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise6/FileRead.java
> +        wordList = wordList.stream()
stream() 깔끔하네요 굿굿

2023-09-27 07:32 UTC, hyeonjaez commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise3/RandomStringArray.java
> +public class RandomStringArray {
코드의 가독성을 높여주고 로컬 변수 또는 매개변수 를 구분하기 위해 this를 쓰는건 어떨까요?

2023-09-27 07:32 UTC, hyeonjaez commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise3/RandomArrayList.java
> +    private double[] list;
클래스 안에 인스턴스 변수 - 생성자 - 메서드 순으로 정렬해주세요

2023-09-27 07:32 UTC, hyeonjaez commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise3/RandomStringArray.java
> +        list = new String[inputNum];
생성자에서 초기화 해주는건 어떨까요??

2023-09-27 08:13 UTC, NANNDA3463 commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise1/Exercise7_1.java
> +        List randomValues = new ArrayList(intNum);
List<Integer> 라고 명시해주면 더욱 좋을 것 같습니다.
ArrayList() 안에 intNum은 없어도 무관할 것 같습니다.

2023-09-27 08:14 UTC, NANNDA3463 commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise2/Exercise7_2.java
> +        int[][] num = { { 10, 11, 12 },
행렬의 자료형 노출을 Class로 추상화해줘도 좋을 것 같습니다.

2023-09-27 08:16 UTC, NANNDA3463 commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise3/RandomArrayList.java
> +public class RandomArrayList {
해당 클래스에서 사용하는 자료형은 Array이니 Array라고만 해줘도 좋을 것 같습니다.

2023-09-27 08:18 UTC, NANNDA3463 commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise3/RandomArrayList.java
> +            System.out.printf("%.4f ", val);
난수 생성을 할 때 소수점이 나올 수 없을 것 같아, .4는 불필요 할 수도 있겠습니다

2023-09-27 08:22 UTC, NANNDA3463 commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise3/RandomStringArray.java
> +                .toString();
멋집니다

2023-09-27 08:25 UTC, NANNDA3463 commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise5/Main.java
> +    public static void printArray(int[] inputArray) {
입력한 값들만 출력해주면 좋을 것 같습니다.
printf로 했으니 format 형식에 맞춰
printf("%d ", val)로 바꿔주면 좋을 것 같습니다.

2023-09-27 08:26 UTC, NANNDA3463 commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise6/FileRead.java
> +    private List<String> wordList = new ArrayList<>();
생성자에서 초기화해주고 final을 붙여도 좋을 것 같습니다.

2023-09-27 08:30 UTC, NANNDA3463 commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise6/FileRead.java
> +    public void wordToList(char oneWord) {
구조가 난해한 것 같습니다...

2023-09-27 08:55 UTC, prospro1 commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise1/Exercise7_1.java
>  */
주석으로 문제 링크 달고 설명해준 거 너무 좋습니다!!! 배워갑니다 감사해요!! :)

2023-09-27 08:58 UTC, prospro1 commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise1/Exercise7_1.java
> +                scanner.nextLine();
catch 해서 여기서 다시 입력을 받아버리는 거 되게 좋은 것 같아요! 처음부터 다시 시작하는 게 아니라 정말 그냥 기회 한 번 더 주는 것 같아서 좋네요 :)

2023-09-27 09:00 UTC, prospro1 commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise1/Exercise7_1.java
> +        List randomValues = new ArrayList(intNum);
없어도 무방하지만 그래도 있으면 이 정도 사이즈는 기본으로 잡아주고 가는 거기도 하고, 만들고 싶은 크기가 이 정도구나를 직관적으로 볼 수 있어서 저는 좋은 것 같습니다..!

2023-09-27 11:24 UTC, hyeonjaez commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise1/Exercise7_1.java
> +                break;
break를 바로 쓰실거면 whlie문을 왜 쓰는지 궁금합니다

2023-09-27 11:24 UTC, hyeonjaez commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise2/Exercise7_2.java
> +    }
와 깔끔하시네요

2023-09-27 11:24 UTC, hyeonjaez commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise3/RandomArrayList.java
> +    public void randomInput(int inputNum) {
입력을 받은게 아니라서 input 이름은 옳지 않은거 같습니다 어떻게 생각하시나요?

2023-09-27 11:24 UTC, hyeonjaez commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise3/Exercise7_3.java
> +        RandomArrayList random2 = new RandomArrayList(200);
정렬 시간을 재는 문제라 같은 배열을 사용해야하지 않을까요??

2023-09-27 11:24 UTC, hyeonjaez commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise3/RandomArrayList.java
> +        return list;
this 키워드를 사용하는게 직관적으로 더 좋지 않을까요?

2023-09-27 11:24 UTC, hyeonjaez commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise5/Main.java
> +            System.out.printf(val + " ");
printf를 쓴 이유가 뭘까요?

2023-09-27 11:24 UTC, hyeonjaez commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise6/FileRead.java
> +        } catch (FileNotFoundException e) {
catch문 || 이걸로 하나로 합치는건 어떨까요?? 그리고 잡은 에러를 왜 다시 던진건가요??

2023-09-27 11:24 UTC, hyeonjaez commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise6/FileRead.java
> +    public void wordToList(char oneWord) {
메서드 명은 앞글자는 동사로 해주세요

2023-09-27 11:43 UTC, prospro1 commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise3/RandomArrayList.java
> +public class RandomArrayList {
저도 동감합니다!

2023-09-27 11:53 UTC, prospro1 commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise3/RandomArrayList.java
> +            System.out.printf("%.4f ", val);
위에 보시면 random.nextDouble() 로 받고 있어서 난수 생성할 때 소수점이 나올 수밖에 없는 것 같습니다..!!

2023-09-27 11:58 UTC, prospro1 commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise3/RandomStringArray.java
> +                if(list[min].compareTo(list[j]) > 0) {
compareTo로 비교한 것도 좋은 것 같습니다!!

2023-09-27 11:59 UTC, prospro1 commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise3/RandomStringArray.java
> +                .toString();
bb

2023-09-27 12:07 UTC, prospro1 commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise6/FileRead.java
> +        wordList = wordList.stream()
bb

2023-09-27 12:09 UTC, prospro1 reviewed
yunhwa reviewed up to all exercises of Chapter 7

2023-10-01 06:00 UTC, minsu11 reviewed
parkminsu code review

2023-10-01 06:00 UTC, minsu11 commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise6/FileRead.java
> +            while (!wordList.isEmpty()) {
file read의 class는 file만 read하는 건 어떨까용? file write는 따로 객체 만드는건 어떨까요?

2023-10-01 06:00 UTC, minsu11 commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise3/RandomArrayList.java
> +    public void printArray() {
출력 결과 떼 배열을 보여주는 메소드를 사용 안하신 것같습니다 출력 결과에 배열이 어떤형태로 되어있는지 안나와있습니다!

2023-10-02 04:20 UTC, nueag commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise1/Exercise7_1.java
> +        Scanner scanner = new Scanner(System.in);
-1 10처럼 첫번째 매개변수에 양의 정수가 아닌 값을 입력하게 되면 스캐너에 10의 값이 남아있게 돼서 while문이 제대로 동작하지 않게 되더라고요! 그래서 밖으로 빼야할 것 같고ㅠ scanner.close()했습니다!

2023-10-02 04:26 UTC, nueag commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise5/Main.java
> +        Scanner scanner = new Scanner(System.in);
수정했습니다!

2023-10-03 07:03 UTC, nueag commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise3/Exercise7_3.java
> +        System.out.println("Arrays.sort Time is: " + compTime);
분리해서 구현했습니다 -!

2023-10-03 07:04 UTC, nueag commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise3/RandomStringArray.java
> +        list = new String[inputNum];
굿 의견입니당 수정했습니다!

2023-10-03 07:12 UTC, nueag commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise1/Exercise7_1.java
> +        List randomValues = new ArrayList(intNum);
좋은 의견 감사합니다! 참고해서 수정했습니당

2023-10-03 07:30 UTC, nueag commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise5/Main.java
> +    public static void printArray(int[] inputArray) {
오 맞습니다 수정했습니다!

2023-10-03 07:41 UTC, nueag commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise6/FileRead.java
> +    public void wordToList(char oneWord) {
맞네요.. 수정했습니다!

2023-10-03 07:42 UTC, nueag commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise1/Exercise7_1.java
> +                break;
catch문으로 에러를 잡는 경우에 다시 실행시키기 위해서 사용했습니다!

2023-10-03 07:43 UTC, nueag commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise2/Exercise7_2.java
> +    }
감솨합니다!

2023-10-03 07:47 UTC, nueag commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise3/RandomArrayList.java
> +    public void randomInput(int inputNum) {
오 따지고 보니 그런 것 같습니다! 수정했습니다

2023-10-03 07:47 UTC, nueag commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise3/Exercise7_3.java
> +        RandomArrayList random2 = new RandomArrayList(200);
예리하십니다 수정했습니당

2023-10-03 07:48 UTC, nueag commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise3/RandomArrayList.java
> +        return list;
수정했습니다 .. ㅎ_ㅎ

2023-10-03 07:48 UTC, nueag commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise5/Main.java
> +            System.out.printf(val + " ");
ㅋㅋ 그러게요 수정했습니다..

2023-10-03 07:49 UTC, nueag commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise6/FileRead.java
> +        } catch (FileNotFoundException e) {
자동완성이었습니다.. 수정했습니다!

2023-10-03 07:50 UTC, nueag commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise6/FileRead.java
> +    public void wordToList(char oneWord) {
맞습니다.. 수정했습니다!

2023-10-03 07:50 UTC, nueag commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise3/RandomStringArray.java
> +                if(list[min].compareTo(list[j]) > 0) {
감사합니당

2023-10-03 07:51 UTC, nueag commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise6/FileRead.java
> +            while (!wordList.isEmpty()) {
예리한 지적입니다 수정했습니다!

2023-10-03 07:51 UTC, nueag commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise3/RandomArrayList.java
> +    public void printArray() {
따로 배열을 출력하지 않고 시간만 출력하도록 구현했습니다!

2023-10-03 08:02 UTC, nueag commented on Chapter7/src/main/java/com/nhnacademy/gaeun/exercise2/Exercise7_2.java
> +        int[][] num = { { 10, 11, 12 },
이게 맞는지 모르겠지만 수정했습니다!

2023-10-04 06:04 UTC, NANNDA3463 approved these changes

2023-10-04 06:04 UTC, NANNDA3463 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise1/Exercise8_1.java
> +            } catch (IllegalArgumentException e) {
InputMismatchException도 catch해주시면 A,B,C 입력받을 때 문자를 입력해도 대처가 가능할 것 같습니다

2023-10-04 06:04 UTC, NANNDA3463 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise1/Exercise8_1.java
> +                int A = scanner.nextInt();
root의 parameter가 double이니 변수들도 double로 만들어주면 좋을 것 같습니다

2023-10-04 07:33 UTC, hyeonjaez commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise3/RomanNumerals.java
> +        if(arabicNumeral > 3999 || arabicNumeral < 0) {
문제에 나와있는 범위가 1 ~ 3999 라서 이 부분 수정 부탁 드립니다

2023-10-04 07:33 UTC, hyeonjaez commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise3/RomanNumerals.java
> +    private int[] critical = {1000, 900, 500, 400, 100, 90, 50, 40, 10 , 9, 5, 4, 1};
이런 변수들은 상수라서 final를 붙혀 주시면 좋겠습니다

2023-10-04 07:33 UTC, hyeonjaez commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise4/Exercise8_4.java
> +        Scanner scanner = new Scanner(System.in);
scanner close 꼭 해주세요

2023-10-04 07:42 UTC, hyeonjaez commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise2/Exercise8_2.java
> +                if(inputNum.equals("")) {
NullPointException 으로 에러 잡으시면 될것 같아요

2023-10-04 07:42 UTC, hyeonjaez commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise2/Exercise8_2.java
> +                if(bigInteger.compareTo(new BigInteger("0"))==-1 || bigInteger.compareTo(new BigInteger("0"))==-0) {
이 문장 해석 좀 부탁드릴게요...

2023-10-04 07:46 UTC, NANNDA3463 requested changes

2023-10-04 07:46 UTC, NANNDA3463 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise2/Exercise8_2.java
> +                while(!bigInteger.equals(new BigInteger("1"))) {
collatz함수를 재귀함수로 만들어도 코드가 간결해질 것 같습니다.

2023-10-04 07:46 UTC, NANNDA3463 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise2/Exercise8_2.java
> +                if(bigInteger.compareTo(new BigInteger("0"))==-1 || bigInteger.compareTo(new BigInteger("0"))==-0) {
-0과 비교하는 건 단순 오타일까요?

2023-10-04 07:46 UTC, NANNDA3463 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise2/Exercise8_2.java
> +        int count = 0;
count를 반복에서 0으로 만들어주는 부분이 없어, 2번째 부턴 다른 답이 나오는 것 같습니다.
혹시 문제가 그렇게 되어 있었나요?

2023-10-04 07:48 UTC, NANNDA3463 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise3/RomanNumerals.java
> +    public void arabicToRoman(int intArabic) {
반례로 CM을 입력했을 때 2000이 나오고 있습니다.

2023-10-04 07:51 UTC, NANNDA3463 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise3/RomanNumerals.java
> +        if(arabicNumeral > 3999 || arabicNumeral < 0) {
로마자 표현도 3999가 마지막인 것 같습니다

2023-10-04 08:50 UTC, NANNDA3463 requested changes

2023-10-04 08:50 UTC, NANNDA3463 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise3/RomanNumerals.java
> +    public void romanToArabic(String roman) {
반례로 CM을 입력했을 때 2000이 나오고 있습니다.
작은 수가 앞에 나오고, 큰 수가 뒤에 나왔을 때 큰 값에서 작은 값을 뺀 값을 뱉어야 합니다.

2023-10-04 08:50 UTC, NANNDA3463 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise3/RomanNumerals.java
> +    public void romanToArabic(String roman) {
배열 구조로 적용하는게 어려울 것 같아 저는 Queue로 했었습니다. 생각보다 간편하니 참고해주세요

2023-10-04 08:50 UTC, NANNDA3463 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise3/RomanNumerals.java
> +    public RomanNumerals(String romanNumeral) {
로마 문자는 같은 문자가 연속으로 4번 이상 들어오면 안된다고 합니다.
이에 대한 처리가 있으면 좋을 것 같습니다.

2023-10-04 08:50 UTC, NANNDA3463 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise4/Exercise8_4.java
> +            } catch (IllegalArgumentException e) {
value로 문자가 들어갔을 경우에 일어나는 InputMismatchException 도 잡아주면 좋을 것 같습니다.

2023-10-04 11:46 UTC, prospro1 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise2/Exercise8_2.java
> +                if(bigInteger.compareTo(new BigInteger("0"))==-1 || bigInteger.compareTo(new BigInteger("0"))==-0) {
보니까 -가 없었을 것 같은데 오타가 맞는 것 같아보여요!! 0과 비교했을 떄 -1이면 음수, 0이면 0이라는 거니까요!

2023-10-04 11:48 UTC, minsu11 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise1/Exercise8_1.java
> +                if(scanner.next().equals("no")) {
yes일 경우에만 loop가 돌아가게 하는건 어떨까요? 그리고 yes랑 no가 아닌 경우에는 다시 물어보게 하는건 어떨까요?

2023-10-04 11:50 UTC, minsu11 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise2/Exercise8_2.java
> +                if(inputNum.equals("")) {
아니면 isEmpty으로 하는 방법도 괜찮을 거 같아요

2023-10-04 11:50 UTC, prospro1 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise2/Exercise8_2.java
> +        if(!value.testBit(0)) {
testBit(0)이 거짓일 때 짝수로 처리해준 거 문제에서 제공한 메서드를 잘 사용한 것 같아 좋습니다  bb

2023-10-04 11:51 UTC, prospro1 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise2/Exercise8_2.java
> +        int count = 0;
처음에 사용자가 입력한 inputNum 부터 시작하는 시퀀스인 것 같습니다! 따라서 count를 1로 시작해주시는 건 어떠신지요 :)

2023-10-04 12:01 UTC, prospro1 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise3/RomanNumerals.java
> +    public RomanNumerals(String romanNumeral) {
3번 이상 들어오면 안된다고 되어있는 것 같습니다...! 참고 부탁드립니다!!

2023-10-04 12:18 UTC, prospro1 reviewed
yunhwa reviewed up to Chapter 8 exercises

2023-10-04 12:58 UTC, minsu11 reviewed
parkminsu code review

2023-10-04 12:58 UTC, minsu11 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise2/Exercise8_2.java
> +                System.out.println("collatz: " + count);
결과 횟수도 좋지만 연산하는 과정 숫자 출력이 있으면 좋을 것 같습니다!

2023-10-04 12:58 UTC, minsu11 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise3/RomanNumerals.java
> +    private int[] critical = {1000, 900, 500, 400, 100, 90, 50, 40, 10 , 9, 5, 4, 1};
critical의 뜻이 무엇인가요?

2023-10-04 12:58 UTC, minsu11 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise3/RomanNumerals.java
> +    public void romanToArabic(String roman) {
반례로 IX 입력시 20이 나옵니다! 참고 해주세요!

2023-10-04 12:58 UTC, minsu11 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise4/Exercise8_4.java
> +        while (true) {
while문을 종료시키는 break구문이 없는 것 같습니다! 추가해주면 좋을 것 같아요!

2023-10-06 01:41 UTC, minsu11 reviewed
parkminsu code review

2023-10-06 01:41 UTC, minsu11 commented on Chapter7/src/main/java/com/nhnacademy/main/exercise1/Exercise7_1.java
> +                int max = scanner.nextInt();
음수 입력 시 throw를 던져주는 부분이 있어야할 것같습니다! -1을 입력했을 경우에 해당 조건에 문제에 맞지 않기 때문에 돌지 않아야하는데 1이라는 값이 저장이 됩니다!

2023-10-06 01:56 UTC, yoho94 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise2/Exercise8_2.java
> +                if(bigInteger.compareTo(new BigInteger("0")) ==-1 || bigInteger.compareTo(new BigInteger("0")) == 0) {
클린 코드를 위해 BigInteger.ZERO를 사용해보는건 어떨까요?

2023-10-06 02:00 UTC, yoho94 approved these changes

2023-10-06 02:00 UTC, khj1994 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise2/Exercise8_2.java
> +                if(bigInteger.compareTo(new BigInteger("0")) ==-1 || bigInteger.compareTo(new BigInteger("0")) == 0) {
compareTo 에서 크고 작고를 비교할때는 -1을 바로 비교하는 것 보다  < 0, > 0 을 사용하는게 좋아요. 명확히 -1을 안돌려주고 음수를 돌려주는경우, 1을 안 돌려주고 양수를 돌려주는 경우가 많습니다.

2023-10-06 02:00 UTC, khj1994 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise2/Exercise8_2.java
> +                if(bigInteger.compareTo(new BigInteger("0")) ==-1 || bigInteger.compareTo(new BigInteger("0")) == 0) {
bigInteger.compareTo(BigInteger.ZERO) <= 0

2023-10-06 02:05 UTC, hyeonjaez commented on Chapter8/src/main/java/com/nhnacademy/main/exercise1/Exercise8_1.java
> +            } catch (IllegalArgumentException e) {
이미 inputUserAnswer에서 IllegalArgumentException을 잡아줘서 main에는 필요 없을 것 같습니다 어떻게 생각하세요?

2023-10-06 02:08 UTC, yoho94 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise3/Roman.java
> +
여기서 private final int value 를 선언하고 아래 생성자에서 초기화 해주고, getter 만들어서 사용하시면 되요 ~~

2023-10-06 02:10 UTC, nueag commented on Chapter7/src/main/java/com/nhnacademy/main/exercise1/Exercise7_1.java
> +                int max = scanner.nextInt();
맞습니다 반영했습니다!

2023-10-06 02:10 UTC, nueag commented on Chapter8/src/main/java/com/nhnacademy/main/exercise1/Exercise8_1.java
> +            } catch (IllegalArgumentException e) {
맞습니다 수정했습니다!

2023-10-06 02:11 UTC, yoho94 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise3/RomanNumerals.java
> +    private Map<Character, Integer> criterias = new HashMap<>();
로마 문자는 2자인 것도 있는데 키가 Character인데 어떻게 했어요?

2023-10-06 02:11 UTC, yoho94 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise3/RomanNumerals.java
> +    private Map<Character, Integer> criterias = new HashMap<>();
추가로 본인이 하려고 했던 이넘으로 한번 해보는건 어떨까요?

2023-10-06 02:16 UTC, yoho94 commented on Chapter8/src/main/java/com/nhnacademy/gaeun/exercise3/RomanNumerals.java
> +        if (Pattern.compile(regex).matcher(romanNumeral).find()) {
romanNumeral.matches(regex); 이걸 사용하는거랑 뭐가 다른가요?

2023-10-12 05:17 UTC, minsu11 approved these changes

2023-10-12 05:29 UTC, prospro1 approved these changes

2023-10-12 08:28 UTC, NANNDA3463 approved these changes

2023-10-12 08:30 UTC, hyeonjaez approved these changes

2023-10-12 08:47 UTC, merged