FEAT Chapter9 exercise
NHN-Default-Project/DefaultProject pull request #27
Opened 2023-10-12 08:53 UTC by minsu11

2023-10-12 10:59 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/functional/Formula.java
> +        if (bigIntegerBigIntegerMap.get(bigInteger) == null) {
"Map.get()" 보단 "Map.computeIfAbsent()을 쓰는 것이 좋다고 합니다.

2023-10-12 10:59 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/functional/Precondition.java
> +public interface Precondition {
@Functional Interface라고 명시해주면 좋을 것 같습니다.

2023-10-12 11:02 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/functional/Main.java
> +            precondition.precondition(str);
기능에 따라 메서드들로 분리하면 좋을 것 같습니다.

2023-10-12 11:19 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/ex/Problem1.java
> +        if (Integer.parseInt(number) <= 0) {
0이 입력된 경우도 포함시켜야 할 것 같습니다!

2023-10-12 11:29 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/ex/MathFormula.java
> +        } else if (number.equals(BigInteger.TWO)) {
number가 2인 경우 부터는 피보나치 공식으로 사용해도 되지 않을까용?

2023-10-12 11:33 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/ex/Calculator.java
> +
ex부분은 안 봐도 된답니다~~

2023-10-12 11:49 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/functional/Main.java
> +            if (Integer.parseInt(str) < 0) {
문자열을 입력한 경우도 고려해주면 좋을 것 같습니당

2023-10-12 12:06 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/internalFI/Main.java
> +                if (Integer.parseInt(string) < 0) {
문자열인 경우도 고려해주면 좋을 것 같습니당

2023-10-12 12:09 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/singletonpattern/Num.java
> +        if (isIntegerNegative(Integer.parseInt(str))) {
문자인 경우도 고려해주면 좋을 것 같습니당

2023-10-12 12:19 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_2/generic/Main.java
> +public class Main {
우리가 약속한 대로 Exercise9_2로 고쳐주면 좋을 것 같습니다.

2023-10-12 12:19 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_2/generic/Node.java
> +public class Node<T extends Comparable<T>> {
Node를 inner class로 만들어주면 좋을 것 같습니다

2023-10-12 12:19 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/generic/Main.java
> +        ReversLinkedList<Integer> reversLinkedList = new ReversLinkedList();
둘 다 똑같은 링크드 리스트의 형식이라면 한가지 LinkedList로 합쳐줄 수 있을 것 같습니다.
LinkedList를 파라미터로 받아서 LinkedList를 리턴하는 메서드를 따로 만들면 어떨까요?

2023-10-12 12:19 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/generic/Main.java
> +            List<Integer> list = factorialLinkedList.createLinkedList(creator, inputData);
Random 객체를 파라미터로 넘겨주면 랜덤을 돌리는 기능까지 factorialLinkedList가 하게 되니까, 이 둘의 기능을 분리하여, 랜덤을 돌려서 나온 값을 받도록 바꿔주면 좋을 것 같습니다.

2023-10-12 12:19 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/generic/factorial/FactorialLinkedList.java
> +    public FactorialLinkedList() {
private가 아니라면 굳이 없어도 될 것 같습니다

2023-10-12 12:19 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/generic/factorial/FactorialLinkedList.java
> +        list.add(RandomNumberFactorial.createRandomData(creator));
RandomNumberFactorial.createRandomData(creator)를 스태틱으로 불러오는 건 결합도가 너무 높은 것 같습니다.

2023-10-12 12:19 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/generic/factorial/FactorialLinkedList.java
> +        List<T> list = new LinkedList<>();
문제의 취지는 ListNode가 들어간 링크드 리스트를 만드는 것이기 때문에 의도와 맞지 않을 것 같습니다.
현 상태에서는 만든 노드가 들어가있지 않습니다.

2023-10-12 12:19 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/generic/ListNode.java
> +    ListNode<T> next;
List의 값을 private으로 가려주는 것이 좋을 것 같습니다.
가려주고 난뒤, constructor로, item 값이 들어오면 item의 값을 바꿔주는 식으로 구현하면 좋을 것 같습니다

2023-10-12 12:19 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_4/Node.java
> +public class Node {
Node를 Tree의 inner Class로 캡슐화하면 좋을 것 같습니다.

2023-10-12 12:19 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_4/Main.java
> +            listSize = Integer.parseInt(inputData(bufferedReader));
프로그램의 기능을 설명해주는 print문이 몇개 있으면 좋을 것 같습니다

2023-10-12 12:19 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_4/Main.java
> +    public static void inputDataToList(BufferedReader br, BinarySortTree list, int size) throws IOException {
Parameter의 이름을 list보단 tree로 바꿔주면 좋을 것 같습니다

2023-10-12 12:19 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_4/BinarySortTree.java
> +            this.root = addNode(this.root, newNode);
문제에서 원한
while the queue is not empty:
  Get a node from the queue
  Print the item in the node
  if node.left is not null:
    add it to the queue
  if node.right is not null:
    add it to the queue
이 사용되지 않은 것 같습니다. 이 때문에 트리 구조가 난해하게 설계 된 듯 합니다.

2023-10-12 12:19 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_5/BinarySearchTree.java
> +        public void setData(T data) {
노드에 data 값이 한번만 수정하는 거라면, 생성자에서 파라미터로 넣어주면 좋을 것 같습니다

2023-10-12 12:19 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_5/BinarySearchTree.java
> +        if (node.data.compareTo(newNode.data) > 0) {
Tree 구조라면 꼭 node의 값을 비교하는 것이 아니라, node의 left와 right가 비어있는지, 아닌지로 판단할 수 있을 것 같습니다.

2023-10-12 12:19 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_5/BinarySearchTree.java
> +    public T search(T value) {
구현이 덜 되었거나 사용이 되지 않는다면 지우면 될 것 같습니다

2023-10-12 12:19 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_6/SimpleParser3.java
> +public class SimpleParser3 {
숫자 3, x * 3 + 1 로 했을 때 값이 12가 나오는 반례가 있습니다

2023-10-12 12:19 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_6/SimpleParser3.java
> +            number = value;
Const는 상수로, 처음 생성자로 입력 받은 값을 리턴하는 것입니다. value의 parameter에 따라 바뀐다면 그건 변수가 되버립니다

2023-10-12 12:19 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_7/SimpleParser3.java
> +        ExpNode derivative() {
나눗셈 미분이 없습니다!

2023-10-12 12:19 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_7/SimpleParser3.java
> +    abstract private static class ExpNode {
printInfix()도 구현해야합니다! Infix는 중위 표기법으로 표기하는 것입니다.

2023-10-12 12:19 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_7/SimpleParser3.java
> +        ExpNode derivative() {
마이너스 연산을 미분하면 오류가 뜰것입니다.
미분하면, -dA 가 나옵니다 이를 구현해주세요

2023-10-12 12:19 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_7/SimpleParser3.java
> +        ExpNode derivative() {
x를 미분하면 상수 1입니다

2023-10-12 12:33 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/functional/Formula.java
> +    static BigInteger fibonacci(BigInteger bigInteger, Map<BigInteger, BigInteger> bigIntegerBigIntegerMap) {
Map 변수명을 좀 더 명확하게 하는게 어떨까요?

2023-10-12 12:33 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/functional/Main.java
> +            precondition.precondition(str);
동의합니다!

2023-10-12 12:33 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/singletonpattern/Exercise9_1.java
> +    public static String inputData() throws IOException {
이 메서드 안쓰시는것 같은데 삭제 해주세요!

2023-10-12 12:33 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/singletonpattern/Num.java
> +    public Num(String str) {
abstract class는 생성자의 접근 제어자가 private으로 알고 있습니다!! 아닌가용?

2023-10-12 12:33 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/singletonpattern/Factorial.java
> +public class Factorial extends Num {
싱글톤 패턴 사용하신것 같은데 보고 배울게용!

2023-10-12 12:33 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/singletonpattern/Num.java
> +        num = new BigInteger(str);
this 키워드를 붙여주는건 어떨까요?

2023-10-13 00:27 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_2/generic/Main.java
> +public class Main {
약속한게 뭔가요? 궁금합니다

2023-10-13 00:31 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_2/generic/BinarySortTree.java
> +        } else {
addNode() 에서 null일때 새로 만들어줘서 여기서 if문을 안하셔도 될것 같습니다 어떻게 생각하시나용?

2023-10-13 01:18 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/generic/ReversLinkedList.java
> +        if (list.size() == listSize) {
이것 보다는 직접 size()를 만들어 보는건 어떨까용??

2023-10-13 01:18 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/generic/ReversLinkedList.java
> +        listSize++;
넣을때마다 증가 시켜주고 만약 삭제 할때 마다 감소 시켜주고 그러면 별로 좋지 않은 코드 인 것 같습니다 size() 메서드를 만들어보는게 좋을 것 같아요 꼭 만들어주세요!!

2023-10-13 01:18 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/generic/factorial/FactorialLinkedList.java
> +    private void addDataToListCustomFuncInterface(Function<Random, T> creator, List<T> list, int listSize) {
왜 linkedlist를 구현 하라고 했는데 왜 기존에 있던 list를 활용할까요 ㅎㅎ

2023-10-13 01:34 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_4/Node.java
> +    public void setData(String data) {
data를 생성자에서 파라미터로 받아주는데 굳이 setter를 쓴 이유가 있을까요? 이런식으로 하시면 data 값을  변경할 수 있게 됩니다. 다시 한번 생각 해주세용~

2023-10-13 01:34 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_4/BinarySortTree.java
> +        size++;
size() 구하는 메서드를 만들어보는게 어떨까요??

2023-10-13 01:34 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_4/Main.java
> +        for (int i = 0; i < binarySortTree.size(); i++) {
queue를 사용 하실거면 조건에 queue가 비어질때 까지 해서 while문으로 해야 좀 더 queue를 잘 활용했다고 생각이 듭니다 게다가 이미 몇번 반복할 건지 정해 두고 하시는데 queue 활용도가 떨어진다고 생각합니다 어떻게 생각하시나요?

2023-10-13 01:42 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/generic/ListNode.java
> +public class ListNode<T> {
이 클래스는 어디에 사용되고 있나요?

2023-10-13 01:56 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/generic/factorial/FactorialLinkedList.java
> +    private void addDataToListCustomFuncInterface(Function<Random, T> creator, List<T> list, int listSize) {
밑에 있는 addDataToListCustomFuncInterface와 어떤 차이가 있는 건가요?

2023-10-13 02:01 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/generic/Main.java
> +        } catch (IOException e) {
하나로 합쳐도 될 것 같습니당

2023-10-13 02:07 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/solution/Main.java
> +            throw new NullPointerException("0을 입력해서 null값이 나옵니다.");
NullPointerException 잡아줘야 할 것 같슴다

2023-10-13 02:07 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/solution/Main.java
> +        } catch (IOException e) {
한줄로 입력할 수 있을 것 같슴다

2023-10-13 02:08 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/solution/factorial/RandomNumberFactorial.java
> +        try {
이 부분에서 오류가 발생할 수 있나요?

2023-10-13 05:51 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/generic/Main.java
> +        ReversLinkedList<Integer> reversLinkedList = new ReversLinkedList();
reverseLinkedList 를 생성하고 여기에 값들을 다 넣은 후에 makeReverseLinkedList 메서드를 호출하는 이유가 reverse 하기 전의 리스트의 값은 더이상 필요 없기 때문일까요~~? 저장공간을 최소화 하기 위해서 그런 것 같기도 한데, 조금 변수명이 헷갈려서 질문드립니다!!

2023-10-13 05:52 UTC, seong1542 commented on Assignment/src/main/java/org/example/parkminsu/dict/test/java/org/example/parkminsu/dict 2/Dic2Test.java
> +                dictionary.load(new CsvParser(), "/Users/minsu/Desktop/DefaultProject/Assignment/src/main/java/org/example/parkminsu/dict/test/resources/test2.csv")
파일 경로를 이렇게 설정하게 되었을때 문제점은 무엇일까요? 어떻게 하면 모든 사람들이 해당 프로젝트를 다운 받았을 때 문제가 발생하지 않을지 생각해보시면 좋을 것 같습니다

2023-10-13 05:52 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_5/BinarySearchTree.java
> +        List<Integer> leafList = findLeafNodeDepths();
이 문장 한줄로 해결 가능 할 것 같습니다

2023-10-13 05:53 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/solution/factorial/RandomNumberFactorial.java
> +        try {
아 아래의 random.nextInt(bound) 부분이 여기 try 부분 안으로 들어와야 하지 않을까요? bound 가 음수가 아니여야 하기 때문인 것 같은데, 그러면 지금 상태로는 catch에 절대 들어가지 않을 것 같아요!!

2023-10-13 05:54 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/solution/factorial/RandomNumberFactorial.java
> +        try {
아니면 bound 가 음수가 아니라는 조건을 걸어주시는 것도 하나의 방법이 될 것 같습니다!!

2023-10-13 05:55 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/test/ReverseLinkedListTest.java
> +
테스트 코드 좋습니다 bb

2023-10-13 06:02 UTC, seong1542 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/functional/Main.java
> +// 효율적인 재귀(memorization)
안쓰시는 코드는 삭제하시고 올려주세요

2023-10-13 06:04 UTC, seong1542 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/functional/Formula.java
> +        if (bigInteger.compareTo(BigInteger.ZERO) == 0) {
compareTo로 사용하셨네요. compareTo도 좋지만 equals를 사용하시면  == 0 과 같은 부분들은 안써도 되서 더 간단명료해보일 것 같습니다

2023-10-13 06:06 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_5/BinarySearchTree.java
> +    public int sumDepthOfLeafNodes() { // leaf node의 depth 총합
이 서브루틴을 만드는 이유가 결국 average를 구하기 위함이었는데 위에서 stream에서 average() 로 바로 반환을 해주시기 때문에 이 서브루틴은 필요가 없을 것 같기도 합니다!!

2023-10-13 06:07 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_5/BinarySearchTree.java
> +    public int countDepthOfLeafNodes() {
count 도 마찬가지로 average를 구하기 위해서였을 거라서, 이것도 필요가 없을 것 같기도 합니다!!

2023-10-13 08:44 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/internalFI/Main.java
> +                if (Integer.parseInt(string) < 0) {
문자열인 경우에는 main문에 IOExceoption에서 잡아주므로 추가하지 않았습니다!

2023-10-13 09:47 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/functional/Formula.java
> +    static BigInteger fibonacci(BigInteger bigInteger, Map<BigInteger, BigInteger> bigIntegerBigIntegerMap) {
수정했습니다!

2023-10-13 09:47 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/functional/Formula.java
> +        if (bigIntegerBigIntegerMap.get(bigInteger) == null) {
수정했습니다!

2023-10-13 09:48 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/functional/Formula.java
> +        if (bigInteger.compareTo(BigInteger.ZERO) == 0) {
수정했습니다!

2023-10-13 09:48 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/functional/Precondition.java
> +public interface Precondition {
수정했습니다!

2023-10-13 09:50 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/functional/Main.java
> +            if (Integer.parseInt(str) < 0) {
문자열인 경우에는 main문에 IOExceoption에서 잡아주므로 추가하지 않았습니다!

2023-10-13 09:52 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/functional/Main.java
> +            if (Integer.parseInt(str) < 0) {
try catch문에서 IOException이 잡아줍니다!

2023-10-13 09:59 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/functional/Main.java
> +            precondition.precondition(str);
수정했습니다!

2023-10-13 10:51 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/singletonpattern/Num.java
> +        if (isIntegerNegative(Integer.parseInt(str))) {
문자인 경우에는 에러이므로 BigInteger 클래스 내부에서 던지면 main문에서 알아서 잡아주는 걸로 알고있습니다!

2023-10-13 10:51 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/singletonpattern/Num.java
> +        num = new BigInteger(str);
수정횄습니다!

2023-10-13 10:52 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/singletonpattern/Num.java
> +    public Num(String str) {
private로 선언을 하면 상속을 받는 클래스들에서 super로 매개변수의 값을 전달 할 수 없어서 public을 구현 했습니다. 현재는 default 수정했습니다!

2023-10-13 11:11 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_2/generic/BinarySortTree.java
> +        } else {
수정 했습니다!

2023-10-13 11:16 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_2/generic/Node.java
> +public class Node<T extends Comparable<T>> {
수정했습니다!

2023-10-13 11:17 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_2/generic/Main.java
> +public class Main {
수정했습니다!

2023-10-13 11:25 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/generic/factorial/FactorialLinkedList.java
> +    public FactorialLinkedList() {
수정했습니다

2023-10-13 11:27 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/generic/factorial/FactorialLinkedList.java
> +    private void addDataToListCustomFuncInterface(Function<Random, T> creator, List<T> list, int listSize) {
매개변수를 보면 해당 메소드는 자바에서 제공하는 Functional Interface로 구현을 한 것이고 아래에 있는 메소드는 제가 만든 Functional interface를 구현했습니다!

2023-10-13 11:31 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/generic/ListNode.java
> +    ListNode<T> next;
수정했습니다

2023-10-13 12:36 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_4/BinarySortTree.java
> +        size++;
size를 구하기 위해서 add를 할 때 field명에 size를 선언 한뒤 add를 하면서 size를 증가 시켰습니다!

2023-10-13 12:41 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_4/Main.java
> +            listSize = Integer.parseInt(inputData(bufferedReader));
수정했습니다!

2023-10-13 12:41 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_4/Main.java
> +    public static void inputDataToList(BufferedReader br, BinarySortTree list, int size) throws IOException {
수정했습니다!

2023-10-13 12:41 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_4/Main.java
> +        for (int i = 0; i < binarySortTree.size(); i++) {
수정했습니다!

2023-10-13 12:47 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_4/Node.java
> +public class Node {
main에서 Queue를 이용해서 print를 해줄 때 Queue의 타입으로 활용이 되서 inner class로 안했습니다!

2023-10-13 12:48 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_4/Node.java
> +    public void setData(String data) {
수정했습니다!

2023-10-13 12:49 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_5/BinarySearchTree.java
> +        if (node.data.compareTo(newNode.data) > 0) {
binary search tree 구조여서 왼쪽과 오른쪽의 데이터를 비교해서 넣었습니다

2023-10-13 12:55 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_5/BinarySearchTree.java
> +    public int sumDepthOfLeafNodes() { // leaf node의 depth 총합
수정했습니다!

2023-10-13 12:57 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_5/BinarySearchTree.java
> +        List<Integer> leafList = findLeafNodeDepths();
변수로 한 번 거쳐서 가독성을 높이려고 변수에 메소드 반환 값을 저장한 뒤  stream으로 return을 한거였습니다! 수정은 했습니다

2023-10-13 13:02 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_6/SimpleParser3.java
> +public class SimpleParser3 {
수정했습니다!

2023-10-13 13:02 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_6/SimpleParser3.java
> +            number = value;
수정 했습니다!

2023-10-14 03:24 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/functional/Main.java
> +// 효율적인 재귀(memorization)
수정했습니다!

2023-10-14 03:41 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_4/BinarySortTree.java
> +            this.root = addNode(this.root, newNode);
트리 구조는 이진 탐색 트리를 사용한 것이고, add 메소드의 조건문이 밑에 있는 addNode의 동일한 구조가 반복되서 헷갈리신 거라고 생각이 됩니다. 현재는 조건문은 삭제를 한 상태이며 
```java
Node newNode = new Node(data);
this.root =  addNode(this.root, newNode);
size++
```
구조로 변경 하였습니다!

2023-10-14 03:43 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_5/BinarySearchTree.java
> +    public int countDepthOfLeafNodes() {
수정했습니다!

2023-10-14 06:02 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/generic/factorial/FactorialLinkedList.java
> +        List<T> list = new LinkedList<>();
수정했습니다!

2023-10-14 06:02 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/generic/factorial/FactorialLinkedList.java
> +    private void addDataToListCustomFuncInterface(Function<Random, T> creator, List<T> list, int listSize) {
수정했습니다!

2023-10-14 06:09 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_5/BinarySearchTree.java
> +    public T search(T value) {
수정 했습니다!

2023-10-14 07:02 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_7/SimpleParser3.java
> +    abstract private static class ExpNode {
구현했습니다!

2023-10-14 07:03 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_7/SimpleParser3.java
> +        ExpNode derivative() {
구현했습니다!

2023-10-14 07:12 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_7/SimpleParser3.java
> +        ExpNode derivative() {
구현했습니다!

2023-10-16 01:57 UTC, seong1542 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/functional/Main.java
> +        }
catch절을 이렇게 사용하는 것보다
catch(IOException | IllegalArgumentException e) 로 작성하시면 catch를 여러번 쓸 필요 없어집니다.

2023-10-16 01:58 UTC, seong1542 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/singletonpattern/Exercise9_1.java
> +            // System.out.println(factorial.apply(factorial.getNum()));
안쓰시는 코드들은 지우고 git에 올려주세요.

2023-10-16 01:58 UTC, seong1542 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/singletonpattern/Exercise9_1.java
> +        }
catch를 계속 해야하는 경우 계속 길어질 것 같죠?

2023-10-16 02:02 UTC, seong1542 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_2/generic/FileHandler.java
> +        TextIO.readFile(path);
혹시 책에서 주어진 TextIO 파일을 사용하신건가요? 아니면 직접 만들어보셨나요?

2023-10-16 02:06 UTC, seong1542 approved these changes
catch절을 여러번 쓰시는 것 같습니다. catch에 써줘야하는 Exception이 많을때 어떻게 하면 좋을까요? 해당 경우에 대해서 조금 더 고민해보시면 좋을 것 같습니다.

2023-10-16 02:23 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/functional/Formula.java
> +        if (bigIntegerBigIntegerMap.get(bigInteger) == null) {
Map.computeIfAbsent는 get을 해서 가져올 때 있으면 그대로 가져오고, 없으면 만들어서 가져오는 메서드입니다!

2023-10-16 02:23 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/functional/Formula.java
> +    static BigInteger fibonacci(BigInteger bigInteger, Map<BigInteger, BigInteger> fibonacciValueMap) {
접근제어자가 필요한 것 같습니다

2023-10-16 03:45 UTC, NANNDA3463 requested changes

2023-10-16 03:45 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/Main.java
> +public class Main {
우리가 약속한대로 Exercise9_3으로 클래스명을 고쳐주시길 바랍니다

2023-10-16 03:57 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/CustomLinkedList.java
> +    ListNode<T> listNode;
접근제어자가 빠졌네요!

2023-10-16 04:37 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/main/exercise9_6/SimpleParser3.java
> + * <factor>  ::=  <number>  |  "(" <expression> ")"
주석이라 프로그램 자체에는 지장이 없지만, <x-variable> 을 추가해주시는 건 어떨까요? 이렇게 BNF 규칙에도 정의되어 있으면 좋을 것 같아요!

2023-10-16 04:39 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/main/exercise9_7/SimpleParser3.java
> + * <factor>  ::=  <number>  |  "(" <expression> ")"
여기도 마찬가지로 <x-variable> 추가해주시면 좋을 것 같습니다 :)

2023-10-16 05:06 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/functional/Formula.java
> +    static BigInteger fibonacci(BigInteger bigInteger, Map<BigInteger, BigInteger> fibonacciValueMap) {
interface에서는 접근 제어자를 쓰지 않습니다!

2023-10-16 05:07 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/functional/Main.java
> +        }
넵! 수정했습니다!

2023-10-16 05:08 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_1/singletonpattern/Exercise9_1.java
> +        }
아하..!! 넵 수정했습니다!

2023-10-16 05:09 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_2/generic/FileHandler.java
> +        TextIO.readFile(path);
책에서 주어진 TextIO사용했습니다!!

2023-10-16 05:10 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/CustomLinkedList.java
> +    ListNode<T> listNode;
수정 했습니다!

2023-10-16 05:45 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/parkminsu/exercise9_3/generic/Main.java
> +        ReversLinkedList<Integer> reversLinkedList = new ReversLinkedList();
현재는 코드가 많이 변경되어서 해당부분은 수정되었습니다!

2023-10-18 00:17 UTC, NANNDA3463 approved these changes

2023-10-18 00:20 UTC, nueag approved these changes

2023-10-18 00:33 UTC, nueag approved these changes

2023-10-18 00:36 UTC, prospro1 approved these changes

2023-10-18 00:37 UTC, merged