yunhwa - chap 09 code review
NHN-Default-Project/DefaultProject pull request #29
Opened 2023-10-12 08:57 UTC by prospro1

2023-10-12 11:29 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_1/Exercise9_1.java
> +                System.out.println("정수로 변환될 수 없는 값이 입력되었습니다. 다시 입력해주세요");
잘못된 value의 값이 들어왔다는 print문이 뜨고 난뒤에 숫자를 입력하면 해당 숫자가 입력값에 안들어가고 nextLine으로 넘어가집니다!

2023-10-12 11:39 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_1/Exercise9_1.java
> +    static Map<BigInteger, BigInteger> factorialMap;
전역변수하는 것도 굉장히 좋지만 main 메서드에 선언을 한 다음에 다른 메서드에는 parameter로 받는 방식으로 하는건 어떨까요??

2023-10-12 11:41 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_1/Function.java
> +public interface Function<T> {
Functional Interface를 구현하시려고 한 것같은데 다시 한번 시도 해보는 것도 좋을 것 같습니다!

2023-10-12 11:43 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_2/SortTreeDemo.java
> +    private static class TreeNode {
해당 Inner Class의 위치를 class 맨 위보단 맨 아래 두는 게 더 깔끔할 것 같습니다!

2023-10-12 11:49 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_2/SortTreeDemo.java
> +    private static void readUserSelectedFile() {
해당 메서드를 밑에 있는 storedStringsInbinarySortTree() 메서드에 사용하시는 건 어떨까요?

2023-10-12 11:54 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_2/SortTreeDemo.java
> +public class SortTreeDemo {
파일을 읽고쓰는 부분과 tree를 구성하는 부분을 따로 객체로 생성해주는 건 어떨까요? 클래스 명이 SortTreeDemo여서 sort tree를 구성하는 객체여야 할 것 같은데 파일도 읽고 쓰는 부분이 자연스럽지 않은 것 같습니다!

2023-10-12 11:55 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_2/Main.java
> +        SortTreeDemo.storedStringsInBinarySortTree();
static으로 만드는 것도 하나의 방법이지만 객체를 생성해서 메서드를 호출하는 방식으로 하시는 건 어떨까요?

2023-10-12 12:02 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_3/Exercise9_3.java
> +            try {
scanner처럼 try resource구문을 사용하시면 밑에 있는 try catch구문을 줄일 수 있을 것 같습니다!

2023-10-12 12:05 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_3/Exercise9_3.java
> +            try {
try resource구문을 쓰신다면 try resource 구문 안에 무한 루프 while을 넣으시면 buffer.reset을 안 쓰는 구조가 될 것 같습니다!

2023-10-12 12:07 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_3/Exercise9_3.java
> +            }
finally 구문을 사용하셔서 Buffer Reader를 닫아 주시면 좋을 것 같습니다!

2023-10-12 12:08 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_3/Exercise9_3.java
> +            }
만약에 try resource구문을 쓰신다면 finally를 안쓰셔도 됩니다!

2023-10-12 12:12 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_3/Exercise9_3.java
> +            } catch (InputMismatchException e) {
만들려고 하는 LinkedList 사이즈에 음수값을 넣었을 경우를 예외처리가 되지 않습니다! -1 100을 입력 시 NullPointerException이 일어납니다!

2023-10-12 12:13 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_1/Exercise9_1.java
> +        Scanner sc = new Scanner(System.in);
try-with-resources 써주면 좋을 것 같습니다!

2023-10-12 12:13 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_3/Exercise9_3.java
> +            } catch (InputMismatchException e) {
10 -1을 입력 시 IllegalArgumentException가 일어납니다! 예외처리가 필요해보입니다!

2023-10-12 12:17 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_4/TreeNodes.java
> +public class TreeNodes { // 만들다가 말고 안사용함. 추후 수정 예정.
제네릭으로 구현을 해보면 어떨까요?

2023-10-12 12:19 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_2/SortTreeDemo.java
> +        while (true) {
반복문 구조도 좋지만 재귀형식으로 insert를 해주는 건 어떨까요?

2023-10-12 12:19 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_4/TreeNodes.java
> +        while (true) {
반복문 구조도 좋지만 재귀형식으로도 해보는건 어떨까요?

2023-10-12 12:33 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_1/Exercise9_1.java
> +    public static void main(String[] args) {
입력 숫자가 음수 일때 에러를 잡고 다시 물어 보는 걸로 해보시는건 어떨까용?

2023-10-12 12:33 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_1/Exercise9_1.java
> +        if (fibonacciMap.containsKey(n)) {
이 구문은 디버그 돌린 결과 들어가지 않습니다.

2023-10-12 12:33 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_1/Exercise9_1.java
> +        if (factorialMap.containsKey(n)) {
mapd을 활용하여 이 구문을 써서 반복한 연산을 하지 않을려고 하신 것 같은데 그러면 1부터 n까지 넣어줘야 하지 않을까요?

2023-10-12 13:02 UTC, minsu11 reviewed
parkminsu code review

2023-10-13 00:25 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_2/Main.java
> +        SortTreeDemo.storedStringsInBinarySortTree();
static으로 하신 이유가 있을까요?

2023-10-13 00:46 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_3/Exercise9_3.java
> +                try {
try-catch 안에 try-catch 이런식으로 남발하시면 에러 잡기도 힘들고 코드의 가독성이 안좋아지는 것 같습니다 메서드를 분리하여 코드를 짜보시는건 어떨까용???

2023-10-13 00:57 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_2/SortTreeDemo.java
> +            if (word != null && ! treeContains(root, word)) {
이 부분에서 중복값이 잡히는 부분이 있는 것 같습니다
값이 있는지 검사할 때에도 소문자로 바꿔서 검사하면 될 것 같아용

2023-10-13 01:13 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_3/Exercise9_3.java
> +                br.mark(10000000);
이거는 무슨 용도인가용? 궁금해서 여쭤봅니다!

2023-10-13 01:19 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_3/Exercise9_3.java
> +                    throw new RuntimeException(ex);
catch에서 던져주고 있는데 이유가 있나용?

2023-10-13 01:54 UTC, NANNDA3463 requested changes
리뷰 제출합니다

2023-10-13 01:54 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_1/Exercise9_1.java
> +public class Exercise9_1 {
피보나치, 팩토리얼의 기능들을 다른 클래스로 분리하여, 객체지향적인 구현을 주면 어떨까요

2023-10-13 01:54 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_2/SortTreeDemo.java
> +public class SortTreeDemo {
동의합니다!

2023-10-13 01:54 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_3/ListNode.java
> +public class ListNode {
getter를 만드셨다면 private로 필드들을 바꿔주면 좋을 것 같습니다.
LinkedList에서 접근해야하는 것이 문제라면, ListNode를 해당 클래스의 inner클래스로 넣어주면 됩니다

2023-10-13 01:54 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_3/Exercise9_3.java
> +                try {
프로그램의 흐름에 따라 하나하나 예외를 던지고 잡는 것 보다도, 내부 기능 메서드들은 예외를 던지기만 하고, 그 메서드를 사용하는 메서드 하나에서만 catch해주는 식으로 구현하면 이해하기 좋을 것 같습니다

2023-10-13 01:54 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_3/LinkedList.java
> +    public void insertNode(int item) {
insert를 할 때, head를 기억해두듯이 tail을 기억해두면 바로 제일 끝 노드로 접근이 가능하여 연산이 줄어듭니다
한번 연습해보세요

2023-10-13 01:54 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_2/SortTreeDemo.java
> +    public static void storedStringsInBinarySortTree() {
해당 메서드가 하는 일이
파일 읽기, 파일을 트리에 저장하기로 두가지인데, 이를 파라미터로 받아와서 처리하도록 메서드를 분리해주면 좋을 것 같습니다

2023-10-13 01:54 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_5/TreeNodes.java
> +    private static TreeNode root;  // Pointer to the root node in a binary tree.
교재에서는 static을 사용하기는 했으나, 
inner static class가 아닌 static 필드는 TreeNodes를 instance로 여러개 만들어도 단 하나의 static 필드를 공유하게 됩니다. 그러면 TreeNodes의 root가 공유하게 되니 오류 가능성이 높아집니다

2023-10-13 01:54 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_4/TreeNodes.java
> +public class TreeNodes { // 만들다가 말고 안사용함. 추후 수정 예정.
해당 클래스는 편의를 위해 메서드들이 모두 static으로 구현되어있는데, 이를 제거하고 구현해보면 객체지향적으로 좋을 것 같습니다

2023-10-13 01:54 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_6/SimpleParser3.java
> +        abstract void printInfixExpression();
infix 구현은 중위순회로 구현이 가능합니다.
BinOpNode의 infix에서
1. 괄호 열기
2. 왼쪽 노드의 infix 호출
3. expression 출력
4. 오른쪽 노드의 infix 호출
5. 괄호 닫기
로 구현해보세요

2023-10-13 12:19 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_1/Exercise9_1.java
> +        Scanner sc = new Scanner(System.in);
수정했습니당 감사합니다!

2023-10-13 14:08 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_1/Exercise9_1.java
> +public class Exercise9_1 {
수정하였습니다 감사합니다!

2023-10-13 14:10 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_1/Exercise9_1.java
> +    static Map<BigInteger, BigInteger> factorialMap;
factorial 이든 fibonacci 든 수학적인 개념이라 항상 어떤 키값에 대한 결과값이 동일하기 때문에 일단 계속 반복해서 사용하고 싶어서 이렇게 작성하긴 했습니다! 그리고 각각의 클래스를 따로 만들어주었기에 보다 좋을 것으로 보입니다!  피드백 감사합니다!

2023-10-13 14:16 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_1/Exercise9_1.java
> +    public static void main(String[] args) {
에러 잡았습니다 감사합니다 :)

2023-10-13 14:24 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_1/Exercise9_1.java
> +                System.out.println("정수로 변환될 수 없는 값이 입력되었습니다. 다시 입력해주세요");
수정했습니다 감사합니다!

2023-10-13 14:25 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_1/Exercise9_1.java
> +        if (factorialMap.containsKey(n)) {
그것도 맞습니다만, 여기서 이 구문을 넣어준 이유는 이후에 여러 번 반복해서 n 값을 입력받아 넣었을 때, 기존에 계산이 이미 되어있던 것에서 바로 반환해서 계산 중복을 없애고자 한 거라서 여기서 사용을 한 겁니다!! 피드백 감사합니당

2023-10-13 14:33 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_1/Exercise9_1.java
> +        if (fibonacciMap.containsKey(n)) {
한 번만 계산을 할 때는 들어가지 않을텐데, 여러 번 계산을 하게 되면 이전까지 계산된 값이 들어갈 거예요!!

2023-10-13 14:33 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_1/Function.java
> +public interface Function<T> {
수정해서 구현했습니다 감사합니다!!

2023-10-13 15:05 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_2/Main.java
> +        SortTreeDemo.storedStringsInBinarySortTree();
수정하였습니다 감사합니다!!

2023-10-13 15:06 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_2/Main.java
> +        SortTreeDemo.storedStringsInBinarySortTree();
음 이유가 딱히 없었던 것 같습니다 수정했습니다!

2023-10-13 15:07 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_2/SortTreeDemo.java
> +public class SortTreeDemo {
교재에 있던 클래스 그대로 가져와 수정만 했었는데, 새로 클래스 구분해서 생성했습니다! 감사합니다!

2023-10-13 15:09 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_2/SortTreeDemo.java
> +    private static class TreeNode {
Inner 클래스의 위치는 개발자의 선택에 따라 다를 수 있고, 일반적으로는 바깥쪽 클래스 바로 아래에 위치시키는 것이 일반적이라고 합니다! 따라서 저는 그대로 두는 게 더 좋을 것 같습니다 ㅎㅎ 피드백 감사합니다!!

2023-10-13 15:11 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_2/SortTreeDemo.java
> +    private static void readUserSelectedFile() {
원래 두 메서드를 아예 결합 안되게 분리하려고 만든 거였는데, 문제는 그렇게 하니까 제대로 입력이 안되는 문제가 생겨서 어쩔 수 없이 아래의 메서드 내에서 호출하는 방식으로 했었던 겁니다! 그래서 메서드가 2개로 있는 것인데, 수정하겠습니다! 감사합니당

2023-10-13 15:19 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_2/SortTreeDemo.java
> +    public static void storedStringsInBinarySortTree() {
ReadFile 을 만들어서 해당 메서드를 넣어주었습니다 피드백 감사합니다!

2023-10-13 15:29 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_2/SortTreeDemo.java
> +    public static void storedStringsInBinarySortTree() {
넵 유사하게 수정했습니다 감사합니다!

2023-10-13 15:31 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_2/SortTreeDemo.java
> +            if (word != null && ! treeContains(root, word)) {
오!! 놓치고 있던 걸 잡아냈어요!! 감사합니당 ㅎㅎ

2023-10-14 16:43 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_2/SortTreeDemo.java
> +        while (true) {
재귀로 하면 stack overflow 가 날 확률도 있고, 이 부분은 교재에 있는 자료를 그대로 가져와서 썼던 거라서 반복문 구조로 되어있는 겁니다! 나중에 시간이 나면 재귀형식으로도 해보겠습니다 피드백 감사합니다!

2023-10-14 16:48 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_3/Exercise9_3.java
> +            try {
아하 그런 방법이 있었군요! 제가 방법을 몰라서 구조가 이렇게 되었는데 피드백 정말 감사합니다 ㅎㅎ 수정했습니다!

2023-10-14 16:51 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_3/Exercise9_3.java
> +                br.mark(10000000);
mark() 메서드는 버퍼 리더가 데이터를 읽을 때 현재 위치를 기억하고, 이후에 reset() 메서드를 호출하여 해당 위치로 다시 돌아갈 수 있도록 하는 거예요!

2023-10-14 16:52 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_3/Exercise9_3.java
> +                br.mark(10000000);
아래의 reset() 과 함께 사용하여 exception 발생 시 다시 반복문을 돌 수 있게 처리한 거였어요!! 그런데 try resources 사용해서 이제 더이상 필요없어져서 삭제했습니당 피드백 감사합니다!

2023-10-14 16:59 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_3/Exercise9_3.java
> +            } catch (InputMismatchException e) {
여기서 예외 처리에 대한 생각을 하지 못했었던 것 같습니다. size 나 랜덤값의 최댓값에 대하여 0 이하의 값에 대해 IllegalArgumentException 이 던져지게 설정 완료하였습니다. 바로 continue; 로 처리해도 무방하나, 일단 이렇게 수정해보았습니다! 피드백 감사합니다!

2023-10-14 17:01 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_3/Exercise9_3.java
> +                try {
sonarInt 에서 잡아준 걸 처리하느라 이렇게 되었습니다. 이렇게 하지 않으면 돌아가지 않았고, 더 간단하게 처리하는 방법을 몰랐기 때문에 그 당시에는 이게 최선이었는데, 지금은 try resouces 를 활용하고 while 문 위치를 try catch 문 밖에서 안으로 옮기게 되면서 해결했습니다! 피드백 감사합니다!

2023-10-14 17:04 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_3/Exercise9_3.java
> +                    throw new RuntimeException(ex);
이렇게 잡아주지 않으면 프로그램이 돌아가지 않아서 sonarlint 추천대로 했던 건데, 지금은 try resources 구문과 while 문 위치의 변경으로 해결했습니다! 피드백 감사합니다!

2023-10-14 17:04 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_3/Exercise9_3.java
> +            }
try resources 구문을 사용하는 것으로 수정하였습니다! 피드백 감사합니다!

2023-10-14 17:51 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_3/LinkedList.java
> +    public void insertNode(int item) {
tail 필드를 만들어주고 그에 맞게 수정해보았습니다! 추천 감사합니다~!

2023-10-14 17:53 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_3/ListNode.java
> +public class ListNode {
innner 클래스로 넣어주는 것으로 수정했습니다! 피드백 감사합니다~!

2023-10-14 17:55 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_4/TreeNodes.java
> +        while (true) {
넵 교재에 있던 걸 그대로 가져와 써서 그런 것인데, 나중에 시간 나면 재귀로도 수정해보도록 하겠습니다 피드백 감사합니다!!

2023-10-14 17:59 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_4/TreeNodes.java
> +public class TreeNodes { // 만들다가 말고 안사용함. 추후 수정 예정.
static 메서드들을 non-static 으로 변경하였습니다! 피드백 감사합니다!

2023-10-14 18:00 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_5/TreeNodes.java
> +    private static TreeNode root;  // Pointer to the root node in a binary tree.
아하 그렇겠군요. 제가 간과한 것 같습니다! 수정했습니다. 피드백 감사합니다!!

2023-10-14 18:03 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_6/SimpleParser3.java
> +        abstract void printInfixExpression();
미분하기 전 expression 을 infix 한 것은 출력이 잘 되었으나, 미분한 결과를 infix 로 출력하는 메서드에서 문제가 발생하였었는데, 같이 고민해주신 바처럼 미분을 두 번 해주는 문제 때문에 출력 자체가 제대로 나오지 않은 거였더라구요! 이제는 수정되었습니다! 정말 감사합니다  :)

2023-10-14 18:19 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_4/TreeNodes.java
> +public class TreeNodes { // 만들다가 말고 안사용함. 추후 수정 예정.
구현 시도해보았습니다! 피드백 감사합니다 :)

2023-10-16 01:11 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/main/exercise9_5/Exercise9_5.java
> +import java.util.Random;
문제 설명을 적어주면 좋을 것 같습니다!

2023-10-16 01:13 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/main/exercise9_5/BinaryTree.java
> +        BinaryTreeNode<T> right;
접근제어자도 써주면 좋을 것 같습니당

2023-10-16 01:19 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/main/exercise9_5/BinaryTree.java
> +    private Map<BinaryTreeNode<T>, Long> getMapOfLeafNode(BinaryTreeNode<T> node, Map<BinaryTreeNode<T>, Long> leafNodeQueue, long depth) {
leafNodeQueue인데 Map이 쓰이고 있는 것 같아서요! 이름을 바꿔주면 어떨까용?

2023-10-16 01:44 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_1/Fibonacci.java
> +    private static Map<BigInteger, BigInteger> fibonacciMap;
static으로 하신 이유가 있을까요?

2023-10-16 02:01 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/main/exercise9_5/Exercise9_5.java
> +import java.util.Random;
수정하였습니다 감사합니다!

2023-10-16 02:03 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_2/BinarySortTree.java
> +    public static class TreeNode {
inner class의 접근 제어자를 public으로 하신 이유가 있을까?

2023-10-16 02:03 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/main/exercise9_5/BinaryTree.java
> +    private Map<BinaryTreeNode<T>, Long> getMapOfLeafNode(BinaryTreeNode<T> node, Map<BinaryTreeNode<T>, Long> leafNodeQueue, long depth) {
수정하였습니다 감사합니다!

2023-10-16 03:12 UTC, minsu11 reviewed
parkminsy code review

2023-10-16 03:12 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_2/BinarySortTree.java
> +    private static TreeNode root;  // 문자열의 이진 트리에서 루트 노드를 나타내는 포인터.
밑에 있는 메소드가 다 static으로 되어 있는데 static으로 하신 이유가 있을까요?

2023-10-16 03:12 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_3/LinkedList.java
> +    class ListNode {
inner class Not-static class로 만드신 이유가 있을까요?

2023-10-16 03:12 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_5/TreeNodes.java
> +            if (((Comparable<T>) newItem).compareTo((T) runner.item) < 0) {
Comparable을 와일카드 형식으로 바꾸시면 newItem.compareTo(runner.item)으로 될 것 같습니다!

2023-10-16 03:12 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_5/TreeNodes.java
> +    private static class TreeNode<T> {
Inner class의 위치가 제일 상단에 있는 건 어떨까요?

2023-10-16 03:56 UTC, NANNDA3463 requested changes

2023-10-16 03:56 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_2/Main.java
> +public class Main {
저희 약속에 따라 Exercise9_2로 클래스명을 바꾸고, 패키지 명도 exercise2로 바꿔주시면 통일성 있을 것 같습니다 다른 패키지들도 해당되니 확인해보세요

2023-10-16 03:56 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_5/TreeNodes.java
> +            if (((Comparable<T>) newItem).compareTo((T) runner.item) < 0) {
generic extends를 활용하여 애초에 comparable 한 것들만 가져올 수 있도록 하는 것도 방법입니다.
예시
```java

public class TreeNodes<T extends Comparable<T>>
```

- 이러면 T에 대해 Comparable이 구현된 녀석들(비교가 가능한 녀석들)만 들어올 수 있게 됩니다
- 지금의 형태는 강제형변환이기 때문에 불안정할 것 입니다

2023-10-17 06:37 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_1/Fibonacci.java
> +    private static Map<BigInteger, BigInteger> fibonacciMap;
값을 저장하고 다시 계산하지 않으려고 이렇게 작성했습니다! 다만, 구조를 전면 개편하느라 추가로 변경하였습니다. 피드백 감사합니다!

2023-10-17 06:42 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_2/Main.java
> +public class Main {
제가 실수했습니다 허허 수정했습니다!

2023-10-17 06:46 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_2/BinarySortTree.java
> +    public static class TreeNode {
아하 private 로 변경해주는 게 더 좋겠네요! 피드백 감사합니다!

2023-10-17 06:47 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_2/BinarySortTree.java
> +    private static TreeNode root;  // 문자열의 이진 트리에서 루트 노드를 나타내는 포인터.
교재에 있던 코드를 가져와서 수정했던 거라서 static 을 수정해야한다는 생각을 미처 못했는데, 다시 생각해보니 static 보다는 트리는 객체로 존재하고 root 도 메서드도 모두 객체일 때 계산되는 게 맞는 것 같아서 non-static 으로 변경하였습니다! 피드백 감사합니다!!

2023-10-17 07:49 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_3/LinkedList.java
> +    class ListNode {
아하 inner class 는 private static class 인 것이 더 좋겠네요 피드백 감사합니다!

2023-10-17 07:52 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_5/TreeNodes.java
> +    private static class TreeNode<T> {
헉 수정했습니다 감사합니다!!

2023-10-17 07:56 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/yunhwa/exercise9_5/TreeNodes.java
> +            if (((Comparable<T>) newItem).compareTo((T) runner.item) < 0) {
피드백 감사합니다! Comparable<T> 를 extends 하는 방식으로 수정했습니다!

2023-10-18 00:17 UTC, minsu11 approved these changes

2023-10-18 00:17 UTC, NANNDA3463 approved these changes

2023-10-18 00:20 UTC, nueag approved these changes

2023-10-18 00:35 UTC, merged