FEAT: chapter9 (gaeun)
NHN-Default-Project/DefaultProject pull request #30
Opened 2023-10-12 09:10 UTC by nueag

2023-10-12 12:56 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Fibonacci.java
> +            return false;
exception class를 직접 만들어서 여기서 던져주는건 어떨까요?

2023-10-12 12:56 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Exercise9_1.java
> +        try (BufferedReader br = new BufferedReader(new InputStreamReader(System.in))) {
BufferedReader 랑 try-with-resources 이용하셨네요 굿입니당

2023-10-12 12:56 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Fibonacci.java
> +    private Fibonacci() {
name space로 하신 이유가 피보나치와 팩토리얼 클래스가 객체 보단 static factory method로 하면 좋을거 같아서 하신 건가요??

2023-10-12 13:09 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Exercise9_1.java
> +    public static boolean calFibonacci(BufferedReader br) throws IOException {
fibonacci를 memoization해주시는 건 어떨까요? 값이 40만 들어와도 현저히 느려집니다!

2023-10-12 13:15 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Factorial.java
> +    private static boolean preCon(BigInteger bigInteger) {
precondition은 두 단어가 아니고 한 단어이기때문에 camel case로 안해도 될 것같습니다!

2023-10-12 13:16 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Factorial.java
> +        if(bigInteger.compareTo(BigInteger.ZERO) <= 0) {
여기있는 수식으로 바로 return을 해주는 건 어떨까요??

2023-10-12 13:21 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Exercise9_1.java
> +    public static boolean calFibonacci(BufferedReader br) throws IOException {
calFibonnacci() method가 계산 해주는 역할이기 때문에 계산 값을 return해주는 방향으로 해주는게 method명이랑 맞는 방향이지 않을까요? 저의 개인적인 생각입니다 하하

2023-10-12 14:01 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Exercise9_1.java
> +    public static boolean calFactorial(BufferedReader br) throws IOException {
해당 메소드와 calFibonacci 메소드의 구조가 동일한데, Functional Interface를 사용하셔서 하나의 메소드로 만들어보시는 건 어떨까요??

2023-10-12 14:04 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Exercise9_1.java
> +    public static boolean calFactorial(BufferedReader br) throws IOException {
그리고 공식을 계산하는 메소드에 값을 입력해서 계산하는 방식도 괜찮지만 따로 입력값을 받는 메소드를 만들어서 입력은 따로 하고 해당 메소드의 매개변수는 적절한 타입으로 바꾸시는 방향으로 하시는 건 어떨까요??

2023-10-12 23:30 UTC, minsu11 reviewed
parkminsu code review

2023-10-12 23:30 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise2/WordTree.java
> +                else
else문에 scop범위를 나타내는 { } 가 추가되면 좋을 것 같습니다!

2023-10-12 23:30 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise2/TreeNode.java
> +public class TreeNode {
TreeNode의 item의 접근 제한자들이 public으로 되어 있기 때문에 item의 값들이 쉽게 변경될 수 있는 우려가 있어보입니다! private를 사용하셔서 get메소드를 활용하는 건 어떨까요?

2023-10-12 23:30 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise2/TreeNode.java
> +public class TreeNode {
exercise9_4번에서도 활용하기 위해서 Tree Node 클래스를 따로 선언해주셨다는건 알고있지만, 해당 TreeNode 클래스를 WordTree Inner Class로 활용하는 건 어떨까요?

2023-10-12 23:30 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/ListNode.java
> +    static ListNode getListNode(int val) {
add method를 구현 해보시는 건 어떨까요?

2023-10-12 23:30 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/ListNode.java
> +public class ListNode {
generic으로 만들어보시는 건 어떨까요??

2023-10-12 23:30 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/Main.java
> +        ListNode listNode1 = ListNode.getListNode(1);
ListNode를 연결 시켜주는 데이터 구조를 만들어 주는건 어떨까요?? 예를 들어 ArrayList, LinkedList, Map 등과 같은 자료 구조가 있을 것 같습니다!

2023-10-12 23:30 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/Main.java
> +        System.out.println("## Origin Linked List");
reverseOrder라는 메서드가 하는 역할이 역순으로 정렬을 해주는 것인데 기존의 노드 값을 print를 해주는 부분은 어색한 것 같은데 어떻게 생각하시나용?

2023-10-12 23:30 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/Main.java
> +        printNode(prevNode);
reverseOrder라는 메서드는 getReverseOrderListHeadNode() 메서드에서 역순으로 정렬된 리스트를 head노드에 저장한 뒤에 return head만 해줘야 할 것 같은데, printNode를 해준 이유가 있을까용? 제 생각에는 printNode는 main 또는 다른 메서드에 호출하는 방향이 괜찮을 것 같은데 혹시 해주신 이유가 있으신가해서 여쭤봅니다!

2023-10-12 23:30 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/Main.java
> +        prePrevNode = null;
해당 구문부터 밑에 printNode 부분이 반복이 되는 구조인거 같은데 반복된 구조는 메서드로 따로 만드시는 건 어떨까요??

2023-10-12 23:30 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/Main.java
> +    private ListNode getReverseOrderListHeadNode(ListNode prePrevNode, ListNode prevNode, ListNode curNode) {
메서드 명이 getReverseOrderListHeadNode인데 매개변수에서 prevNode 변수명을 head라고 바꾸는건 어떻게 생각하실까용?

2023-10-12 23:30 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/Main.java
> +    private ListNode getReverseOrderListHeadNode(ListNode prePrevNode, ListNode prevNode, ListNode curNode) {
아니면 return을 할 때 head를 사용하는건 어떨까요? 이건 개인적인 의견입니다!

2023-10-12 23:30 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/Main.java
> +    public ListNode reverseOrder(ListNode head) {
역순된 리스트의 값을 순회하면서 값을 출력하니깐 printReverseOrderTraversal 같이 순회라는 의미를 추가해주는 건 어떨까요??

2023-10-12 23:30 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise4/Exercise9_4.java
> +        TreeNode treeNode1 = new TreeNode("1");
TreeNode의 구조를 연결 시켜줄 자료 구조 클래스를 만들어주는 건 어떨까요?

2023-10-12 23:30 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise4/Exercise9_4.java
> +        treeNode1.left = treeNode2;
많은 데이터가 필요한 상황이 된다면 해당 구문을 많이 반복하는 하드코딩이 될 것 같은데 add 메소드를 구현하시는 건 어떨까요?

2023-10-12 23:30 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise4/Exercise9_4.java
> +        TreeNode treeNode1 = new TreeNode("1");
문자열뿐만 아니라 다른 타입의 값들도 저장이 가능하도록 제네릭을 사용하시는 건 어떨까요?

2023-10-12 23:30 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise4/Exercise9_4.java
> +    private static Queue<TreeNode> queue = new LinkedList<>();
해당 변수를 static으로 구현하신 이유가 있으실까요? 가은씨의 의견이 듣고 싶어서 코멘트 남겼습니다!

2023-10-12 23:30 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/BinaryTree.java
> +    private int SIZE = 1023;
size를 지정해줘서 해당 트리의 size의 값을 얻어내는 것이 아니라 Node가 추가 되었을 때 size의 값이 변경이 되서 값을 얻어내는 방식은 어떨까요?

2023-10-12 23:30 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/BinaryTree.java
> +    public BinaryTree() {
생성자에서 트리만들기, 리프노드의 합계, 최대 깊이 등과 같이 너무 많은 일을 하는 것같습니다! 생성자에는 생성만 해주는게 좋을 것 같은데 어떻게 생각하시나요??

2023-10-12 23:30 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/BinaryTree.java
> +    private int maxDepth = 0;
생성자에서 초기화를 해주는건 어떨까요?

2023-10-12 23:30 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/BinaryTree.java
> +        System.out.println("모든 잎의 평균 깊이: " + sum / countNode);
this를 사용해주시는 건 어떨까영?

2023-10-12 23:30 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/BinaryTree.java
> +public class BinaryTree {
다양한 타입들이 들어올 수 있게 제네릭으로 구현해보시는 건 어떨까요?

2023-10-12 23:30 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/Exercise9_5.java
> +        binaryTree.treeInsert();
메인에서도 treeinsert()를 하면 1023개가 아닌 2046개의 트리가 생성이 될 것 같습니다! 해당 구문은 사용을 안한다면 삭제해도 될 것 같습니다!

2023-10-12 23:30 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise6/SimpleParser3.java
> +            TextIO.skipBlanks();
정수를 입력을 받는다는 출력문이 있으면 좋을 것같습니다!

2023-10-13 00:22 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise2/FileRead.java
> +                for(String newItem : wordOneLine) {
이 for문까지 stream 으로 하는건 어떨까요?

2023-10-13 00:22 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise2/WordTree.java
> +        while (true) {
메서드를 분리해 보는건 어떨까요?

2023-10-13 00:39 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/Main.java
> +        ListNode listNode4 = ListNode.getListNode(4);
insert()를 구현해보시는건 어떨까요?

2023-10-13 01:57 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise4/Exercise9_4.java
> +        TreeNode treeNode3 = new TreeNode("3");
하드 코딩 하시면 안됩니다 insert()구현 해주세용ㅎ

2023-10-13 01:57 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/Node.java
> +    Node parent;
트리 구조라서 parent는 적절하지 않은것 같습니다!

2023-10-13 01:57 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/Node.java
> +    public int depth;
node 클래스는 자신의 value와 left, right만 필요하고 그 녀석의 깊이는 따로 메서드로 구하게 하는건 어떠실까요?

2023-10-13 01:57 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/BinaryTree.java
> +    public static Node addNode(Node node, Node newNode) {
static으로 구현 하신 이유가 있으실까요?

2023-10-13 02:13 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Exercise9_1.java
> +    public static boolean calFibonacci(BufferedReader br) throws IOException {
동의합니다

2023-10-13 02:17 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Fibonacci.java
> +    private Fibonacci() {
class로 만들고 팩토리얼과 피보나치 계산을 수행하는 다른 클래스를 하나 더 만들거나,

Fibonacci와 Factorial 모두 BigInteger를 파라미터와 리턴값으로 쓰는 것이니 이를 Functional Interface로 구현하여 전체 클래스의 개수를 줄이는 식으로 구현할 수도 있습니다.

2023-10-13 02:27 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise2/WordTree.java
> +    private static TreeNode root;
static 필드는 모든 인스턴스 클래스에 대해 하나만 존재하므로, WordTree를 여러 개 만들어도 root가 동일하게 됩니다. 클래스로 수정해봅시다

2023-10-13 02:27 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/ListNode.java
> +    static ListNode getListNode(int val) {
Node가 다른 Node를 생성하여 내보낸다는 건 객체의 역할을 벗어나는 것 같습니다. 아마 Tree가 없는 게 문제인 듯 싶으니 Tree 클래스를 만들어서 inner class로 노드를 넣어주세요

2023-10-13 03:32 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/Main.java
> +        ListNode listNode1 = ListNode.getListNode(1);
혹시 싱글톤 패턴을 구현하는 것이 목적이었을까요?
패턴에서의 getInstance의 기능과 유사해보입니다.

2023-10-13 03:53 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/Main.java
> +class Solution {
inner클래스인 게 아니라면 다른 파일로 분리해주는 게 좋을 것 같습니다!

2023-10-13 03:53 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/Main.java
> +        System.out.println("## Origin Linked List");
SRP에 따라 메서드로 분리해주면 좋을 것 같습니다

2023-10-13 03:53 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise2/TreeNode.java
> +public class TreeNode {
가독성을 위해 같은 코드더라도 패키지가 다르면 복사해서 사용해주면 좋을 것 같습니다!

2023-10-13 03:53 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise4/Exercise9_4.java
> +        queue.add(head);
- iterator 패턴과 유사한데, 한번 iterator를 구현해보면 좋을 것 같습니다!
- 해당 메서드는 삽입의 역할을 갖고 있으므로, queue를 parameter로 받아서 출력하는 메서드를 만들면 공부하는 데 좋을 것 같습니다!

2023-10-13 03:53 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise6/SimpleParser3.java
> +        ExpNode derivative() {
해당 메서드는 미분만 하는 것이므로 printInFix가 굳이 필요 없을 것 같습니다

2023-10-13 03:53 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise6/SimpleParser3.java
> +public class SimpleParser3 {
printInfix의 구현은 매우 잘 됐지만, 중위 순회라고 생각하면 좀 더 코드를 줄일 수 있습니다

다음을 참고해보세요
- 괄호 열기
- 왼쪽 노드의 infix 호출
- expression 출력
- 오른쪽 노드의 infix 호출
- 괄호 닫기

2023-10-13 03:57 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Fibonacci.java
> +            return BigInteger.ONE;
fibonacci(7) 을 계산했을 때 fibonacci(8) 값인 21이 나오는 것 같습니다!

2023-10-13 03:58 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Fibonacci.java
> +            return BigInteger.ONE;
여기서 zero 일 때 one 으로 해줘서 그런 것 같은데요, fibonacci(0) = 0, fibonacci(1) = 1 이고, 따라서 fibonacci(2) = f(1) + f(0) = 1 + 0 = 1  인데, 여기서 1로 해주게 되면 이후에

2023-10-13 04:07 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise2/FileRead.java
> +        wordTree = new WordTree();
this 붙여주시면 더 좋을 것 같습니다 ㅎㅎ

2023-10-13 04:09 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/ListNode.java
> +    static ListNode getListNode(int val) {
저도 동감합니다!

2023-10-13 04:20 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise4/Exercise9_4.java
> +        queue.add(head);
------------------
음 저는 생각이 좀 다른 게, 예제에서 서브루틴을 위한 알고리즘을 제공했고 이 코드는 사실상 문제에서 제공된 알고리즘을 그대로 구현으로 옮긴 코드라서 문제는 없을 것 같습니다! 저도 동일하게 코드를 짰기 때문에 코멘트 남깁니다! 

------------

다만 저도 가은씨도 공부하는 차원에서 다른 방식으로 코드를 짜보는 것도 좋을 것 같긴 합니다!

2023-10-13 04:25 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/BinaryTree.java
> +    public int calLeafNodeVal(Node node) { //노드 총 개수
노드의 총 개수를 구하는 메서드라면 val 보다는 cnt 나 num 으로 표현해주는 게 더 좋지 않을까요~~?

2023-10-13 04:38 UTC, prospro1 reviewed
yunhwa reviewed almost the exercises of chap09 !

2023-10-13 07:25 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/Node.java
> +    Node parent;
가 아니라 parent를 잘 활용하지 않아서 있어야 할 이유가 없는것 같습니다

2023-10-13 11:47 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise4/Exercise9_4.java
> +    private static Queue<TreeNode> queue = new LinkedList<>();
main파일에 만드느라 부득이하게 사용했습니다.. main 안으로 넣도록 할게요 ㅎㅎ

2023-10-13 11:55 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise4/Exercise9_4.java
> +        queue.add(head);
좋은 의견 감사합니다!

2023-10-13 11:56 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise4/Exercise9_4.java
> +        TreeNode treeNode3 = new TreeNode("3");
ㅎㅎ넵!

2023-10-13 11:56 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise4/Exercise9_4.java
> +        treeNode1.left = treeNode2;
저도 동의합니다

2023-10-13 15:26 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Exercise9_1.java
> +    public static boolean calFactorial(BufferedReader br) throws IOException {
factorial 함수는 인터페이스로 구현해보았습니다. fibonacci는 잘 되지 않았는데 아무래도 재귀적으로 값을 계산해주기 때문에 함수형 인터페이스로 구현하기 보다는 말씀해주신 것처럼 Map을 이용해서 계산하는 방식으로 수정했습니다!

2023-10-13 15:26 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Exercise9_1.java
> +    public static boolean calFibonacci(BufferedReader br) throws IOException {
수정했습니다!

2023-10-13 15:29 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Fibonacci.java
> +            return BigInteger.ONE;
감사합니다! 수정했습니당

2023-10-14 05:24 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Exercise9_1.java
> +    public static boolean calFactorial(BufferedReader br) throws IOException {
인터페이스로 구현해보았습니다!

2023-10-14 05:24 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Factorial.java
> +    private static boolean preCon(BigInteger bigInteger) {
수정했습니당

2023-10-14 05:24 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Factorial.java
> +        if(bigInteger.compareTo(BigInteger.ZERO) <= 0) {
좋은 의견입니당

2023-10-14 05:26 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Fibonacci.java
> +    private Fibonacci() {
좋은 의견 감사합니다!

2023-10-14 05:28 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Fibonacci.java
> +    private Fibonacci() {
넵 그래서 private으로 생성자를 두었는데 이것보다는 말씀해주신 것처럼 클래스 하나로 합치고 인터페이스로 구현하는게 더 좋은 것 같아서 수정했습니당

2023-10-14 05:28 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Fibonacci.java
> +            return false;
오! 해보겠습니당 ㅎ_ㅎ

2023-10-14 05:42 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise2/FileRead.java
> +        wordTree = new WordTree();
수정했슴당ㅎㅎ

2023-10-14 05:42 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise2/FileRead.java
> +                for(String newItem : wordOneLine) {
수정했습니다!

2023-10-14 05:57 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise2/TreeNode.java
> +public class TreeNode {
FileWrite에서 TreeNode가 사용되기 때문에 외부 클래스로 구현했습니다! WordTree의 inner class로 변경하였고 fileWrite클래스에서 import하는 방식으로 수정했습니당

2023-10-14 05:59 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise2/WordTree.java
> +    private static TreeNode root;
앗 수정했습니다

2023-10-14 05:59 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise2/WordTree.java
> +        while (true) {
사용되지 않는 메소드라서 삭제하였습니다!

2023-10-14 05:59 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise2/WordTree.java
> +                else
사용되지 않는 메소드라서 삭제하였습니다!

2023-10-14 06:41 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/ListNode.java
> +public class ListNode {
수정했습니다!

2023-10-14 06:41 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/ListNode.java
> +    static ListNode getListNode(int val) {
수정했습니다!

2023-10-14 06:42 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/Main.java
> +        ListNode listNode1 = ListNode.getListNode(1);
죄송합니다,, 파일에 문제가 많아서 대거 수정했습니다

2023-10-14 06:42 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/Main.java
> +        ListNode listNode4 = ListNode.getListNode(4);
수정했습니다!

2023-10-14 06:43 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/Main.java
> +class Solution {
수정했습니다!

2023-10-14 06:43 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/Main.java
> +    public ListNode reverseOrder(ListNode head) {
수정했습니다!

2023-10-14 06:44 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/Main.java
> +        System.out.println("## Origin Linked List");
죄송합니다,, 파일에 문제가 많아서 대거 수정했습니다

2023-10-14 06:44 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/Main.java
> +        printNode(prevNode);
죄송합니다,, 파일에 문제가 많아서 대거 수정했습니다

2023-10-14 06:44 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/Main.java
> +        prePrevNode = null;
죄송합니다,, 파일에 문제가 많아서 대거 수정했습니다

2023-10-14 06:44 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/Main.java
> +    private ListNode getReverseOrderListHeadNode(ListNode prePrevNode, ListNode prevNode, ListNode curNode) {
죄송합니다,, 파일에 문제가 많아서 대거 수정했습니다

2023-10-14 07:01 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/BinaryTree.java
> +public class BinaryTree {
수정했습니다!

2023-10-14 07:02 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/BinaryTree.java
> +    private int maxDepth = 0;
수정했습니다!

2023-10-14 07:02 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/BinaryTree.java
> +    public BinaryTree() {
동의합니다 수정했습니다!

2023-10-14 07:02 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/BinaryTree.java
> +        System.out.println("모든 잎의 평균 깊이: " + sum / countNode);
수정했슴당

2023-10-14 07:03 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/BinaryTree.java
> +    public static Node addNode(Node node, Node newNode) {
그러게요??.. 수정했습니다!

2023-10-14 07:03 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/BinaryTree.java
> +    public int calLeafNodeVal(Node node) { //노드 총 개수
맞습니다 처음에 값을 구하는 걸로 착각하고 저렇게 지었는데 수정을 안 했네요.. 수정했습니다!

2023-10-14 07:05 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/Exercise9_5.java
> +        binaryTree.treeInsert();
오 맞네요.. 수정했습니다!!

2023-10-14 07:05 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/Node.java
> +    Node parent;
수정했습니당

2023-10-14 07:05 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/Node.java
> +    public int depth;
그게 맞는 것 같습니다 수정했습니다!

2023-10-14 07:06 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/BinaryTree.java
> +    private int SIZE = 1023;
해당 문제에서 size의 값이 지정되었기 때문에 따로 추가하지 않았습니다! 변경되지 않기 때문에 final로 수정했습니다!

2023-10-14 07:30 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise6/SimpleParser3.java
> +public class SimpleParser3 {
이해했습니다 감사합니다!! 수정했습니당

2023-10-14 07:31 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise6/SimpleParser3.java
> +        ExpNode derivative() {
맞습니다 수정했습니당

2023-10-14 07:31 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise6/SimpleParser3.java
> +            TextIO.skipBlanks();
변수를 입력할 경우에는 정수를 먼저 입력하라는 문장을 추가했습니다

2023-10-16 01:51 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Exercise9_1.java
> +    public static boolean isSetFactorialVal(BufferedReader br) throws IOException {
이 메서드가 하는 일이 입력받고 factorial 계산도 하고 등등 이 친구가 하는 행동이 한개로 줄여보고 나눠보는건 어떨까요?
그리고 main에 while문을 써서 입력을 제대로 못받으면 다시 입력 받게끔 되어있는데 이 메서드 내부에서 처리해주는건 어떨까요?

2023-10-16 01:51 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Exercise9_1.java
> +    public static boolean isSetFibonacciVal(BufferedReader br) throws IOException {
이 메서드도요

2023-10-16 01:51 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Fibonacci.java
> +public class Fibonacci {
fibonacci의 값이 너무 커지면 시간이 너무 오래걸립니다. 
성능 향상을 위해 memorization기법을 사용해 보시는건 어떨까요?

2023-10-16 01:51 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise2/FileWrite.java
> +            FileWriter fileWriter = new FileWriter(path, true);
try-with-resources를 쓰는건 어떨까요?

2023-10-16 01:51 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/ListNode.java
> +    private Node root;
연결 리스트는 root 이름 보단 head이름이 더 적절한 것 같습니다 어떻게 생각하세요?

2023-10-16 01:51 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/ListNode.java
> +        protected Node next = null;
제네릭으로 하셨는데 여기서부터 모든 Node들을 Node<T>로  붙여주지 않은 이유가 있을까요?

2023-10-16 01:51 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise4/Exercise9_4.java
> +        Queue<TreeNode> queue = new LinkedList<>();
BinaryTree클래스에서 printQueue 메서드에서 파라미터로 queue를 받아서 출력 하셨는데 제 생각에는 저 메서드에서 queue를 받지않고 처리해도 될 것 같습니다 
어떻게 생각하시나요?

2023-10-16 01:51 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/BinaryTree.java
> +            add(random.nextDouble() * 1024);
main에서 처리 해주는건 어떨까요? 이 객체가 자기가 스스로 트리를 만드는건 아니라는 생각입니당!

2023-10-16 01:51 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/BinaryTree.java
> +        countNode++;
이 친구가 전역변수인 것을 알기 위해 this.라는 키워드를 사용해보는건 어떨까요?

2023-10-16 01:51 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/BinaryTree.java
> +    public  Node addNode(Node node, Node newNode) {
이 메서드는 접근제어자 private로 설정해도 될 것 같아요

2023-10-16 01:51 UTC, hyeonjaez commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/BinaryTree.java
> +public class BinaryTree {
Node 클래스는 제네릭으로 하셨는데 이 클래스도 제네릭으로 해보시는건 어떨까요?

2023-10-16 02:09 UTC, NANNDA3463 requested changes

2023-10-16 02:09 UTC, NANNDA3463 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/ListNode.java
> +    protected static class Node<T> {
protected 접근 제한자는 상속 관계에게 접근을 허용하는 것인데, inner class는 private로 하셔도 바깥의 ListNode 클래스에서도 접근이 가능합니다. 그래서 protected는 사용이 다른 것 같습니다

2023-10-16 03:14 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Exercise9_1.java
> +
예외처리에 관한 출력문이 있는건 어떨까요?

2023-10-16 03:22 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Fomula.java
> +    public static BigInteger factorial(BigInteger bigInteger) {
매개변수를 functional interface를 받으면 음수 체크하는 메소드를 하나로 만들 수 있지 않을까요??

2023-10-16 03:35 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise2/FileWrite.java
> +    public static void treeList(WordTree.TreeNode node, FileWriter fileWriter) throws IOException {
inner class인 WordTree.TreeNode를 매개변수로 받아서 하는 방식도 괜찮지만, 매개변수에 WordTree 타입만 받고 WordTree에 add 메소드를 구현을 한 다음에 add 메소드를 활용해서 Tree를 만드시는 건 어떨까요??

2023-10-16 03:38 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise2/WordTree.java
> +    protected static class TreeNode {
protected로 하신 이유가 있을까요?

2023-10-16 03:41 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise4/TreeNode.java
> +    public TreeNode right;
같은 패키지에만 활용이 된다면 default로 해도 괜찮을 거 같은데 public으로 하신 이유가 있을까요?

2023-10-16 03:41 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise4/TreeNode.java
> +    public TreeNode right;
그리고 inner class가 아닌 따로 클래스를 만들어주신 이유가 있을까요?

2023-10-16 03:43 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/BinaryTree.java
> +    public BinaryTree() {
굳입니다👍

2023-10-16 03:47 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise4/Exercise9_4.java
> +    private static Queue<TreeNode> queue = new LinkedList<>();
넵!

2023-10-16 03:49 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/BinaryTree.java
> +    private int SIZE = 1023;
넵! 알겠습니다!

2023-10-16 03:56 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/Node.java
> +    public T value;
value 값을 public하신 이유가 있을까요??

2023-10-16 03:58 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/Node.java
> +        if(node.value instanceof Double) {
node에서 compareTo를 하는 것도 좋은 방식이지만, 이 경우에는 double의 값만 비교하는게 아쉬운것 같습니다!! Node 클래스에서 Comparable를 implement를 하는 것이 아닌 BinaryTree에서 <T extend Comparable<T>>로 하시면 어떨까용?

2023-10-16 03:58 UTC, minsu11 reviewed
parkminsu code review

2023-10-16 04:08 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise6/Exercise9_6_7.java
> + * <factor>  ::=  <number>  |  "(" <expression> ")"
여기에 <x-variable> 추가해주시면 더 좋지 않을까요? :) 
<factor>  ::=  <number>  |  <x-variable>  |  "(" <expression> ")"

2023-10-16 04:12 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise6/Exercise9_6_7.java
> +                System.out.println("\nValue is " + exp.derivative().value(xValue));
도함수에 xValue 대입한 결과 값이라면, 위의 Value 와 구분되게 Derivative value is 라고 출력해주시는 건 어떠신가요~?

2023-10-16 04:15 UTC, prospro1 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise6/Exercise9_6_7.java
> +                exp.printInfix();
그리고 이렇게 되면 미분하기 전 원래 식의 stack commands 와 중위 표기법이 출력되는 것 같은데요, 문제 7번에서는 미분한 식의 중의 표기법을 출력하라고 되어있었어서, 미분한 도함수의 printInfix도 추가로 출력해주시면 더 좋을 것 같습니다!

2023-10-16 04:45 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Fibonacci.java
> +public class Fibonacci {
map을 써서 구현했는데 put을 안 하고 있었네요.. 감사합니다! 수정했습니다!

2023-10-16 04:47 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise1/Exercise9_1.java
> +
수정하였습니다!

2023-10-16 04:53 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise2/WordTree.java
> +    protected static class TreeNode {
수정했습니다!

2023-10-16 04:53 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise2/FileWrite.java
> +            FileWriter fileWriter = new FileWriter(path, true);
수정했습니다!

2023-10-16 04:59 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise2/FileWrite.java
> +    public static void treeList(WordTree.TreeNode node, FileWriter fileWriter) throws IOException {
해당 메소드는 트리를 만드는게 아니라 fileWriter를 이용해서 파일에 트리의 노드값들을 써주고있습니다! 메소드 명이 적절하지 않은 것 같아서 수정했습니다!

2023-10-16 05:02 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/ListNode.java
> +    protected static class Node<T> {
protected가 같은 패키지 내의 파일을 접근할 때 쓰는건줄 알았습니다.. 알려주셔서 감사합니다!!

2023-10-16 05:02 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/ListNode.java
> +    private Node root;
듣고보니 그렇습니다!

2023-10-16 05:06 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise3/ListNode.java
> +        protected Node next = null;
맞네요.. 수정했습니다!

2023-10-16 05:09 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/BinaryTree.java
> +public class BinaryTree {
수정했습니다!

2023-10-16 05:09 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/BinaryTree.java
> +        countNode++;
수정했습니다!

2023-10-16 05:10 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/BinaryTree.java
> +    public  Node addNode(Node node, Node newNode) {
맞습니다 수정했습니다!

2023-10-16 05:10 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/BinaryTree.java
> +            add(random.nextDouble() * 1024);
오 알겠습니다!

2023-10-16 05:22 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/Node.java
> +    public T value;
hahaha 수정했습니다

2023-10-16 05:34 UTC, nueag commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise5/Node.java
> +        if(node.value instanceof Double) {
오!!! instanceof 안 쓰고 싶었는데 T extends 해주고 데이터 값으로 비교하면 알아서 해주네요! 감사합니다 ㅎㅎ

2023-10-16 06:05 UTC, minsu11 commented on Chapter9/src/main/java/com/nhnacademy/gaeun/exercise6/Exercise9_6_7.java
> + * <factor>  ::=  <number>  |  "(" <expression> ")"
수정했습니다!

2023-10-18 00:16 UTC, minsu11 approved these changes

2023-10-18 00:17 UTC, NANNDA3463 approved these changes

2023-10-18 00:29 UTC, prospro1 approved these changes

2023-10-18 00:34 UTC, merged