Code review [chapter04]
NHN-Default-Project/DefaultProject pull request #9
Opened 2023-09-18 06:57 UTC by 20203174

2023-09-18 08:25 UTC, NANNDA3463 approved these changes

2023-09-18 08:25 UTC, NANNDA3463 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise01/Main.java
> +        printCapitalized(userInput);
scanner를 close하면 어떨까요?

2023-09-18 08:25 UTC, NANNDA3463 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise01/Main.java
> +                newString += Character.toUpperCase(checkSentence[i]);
현재 코드로는 각 단어의 첫 글자만 대문자가 되는 게 아니라 모든 문자가 대문자가 되는 것 같아요

2023-09-18 08:25 UTC, NANNDA3463 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise02/Main.java
> +            case 'A':
소문자 a, b, c, d, e, f에 대한 고려가 되지 않은 것 같아요

2023-09-18 08:25 UTC, NANNDA3463 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise03/Main.java
> +        System.out.println(diceRoll(scanner.nextInt()));
scanner로 int가 아닌 값이 왔을 때의 Exception을 처리하면 어떨까요? 
scanner.close()도 하면 좋을 것 같습니다

2023-09-18 08:25 UTC, NANNDA3463 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise03/Main.java
> +            rollingNumber++;
첫 반복문에서 조건문을 만족하면 rollingNumber가 1 더해지지 않을 것 같습니다

2023-09-18 08:27 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise01/Main.java
> +        printCapitalized(userInput);
try-catch resource로 하는 것도 괜찮아 보입니다~~

2023-09-18 08:29 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise01/Main.java
> +                newString += Character.toUpperCase(checkSentence[i]);
동의합니당~!! boolean 변수 하나랑 조건문을 추가하면 될 거같아용

2023-09-18 08:31 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise02/Main.java
> +            case 'A':
동의합니다

2023-09-18 08:33 UTC, NANNDA3463 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise04/Main.java
> +        while (dice() + dice() != goalValue) {
첫 반복문에서 조건문을 만족하면 rollingNumber가 1 더해지지 않을 것 같습니다
do-while도 한 방법이 될 수 있을 것 같아요

2023-09-18 08:36 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise03/Main.java
> +        System.out.println(diceRoll(scanner.nextInt()));
try-catch release 구문을 이용해보면 좋을 것같습니다.

2023-09-18 08:37 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise03/Main.java
> +            rollingNumber++;
아니면 rollingNumber의 초기값을 1로 줘도 괜찮을 것 같아요

2023-09-18 08:42 UTC, NANNDA3463 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise08/QuizGame.java
> +    QuizGame() {
public 같은 Access modifier가 있으면 어떨까요?

2023-09-18 08:43 UTC, NANNDA3463 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise08/QuizGame.java
> +            firstNum[i] = random.nextInt(100);
this.를 통해 명시해주면 더 좋을 것 같습니다!

2023-09-18 08:45 UTC, NANNDA3463 approved these changes

2023-09-18 08:45 UTC, NANNDA3463 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise08/Main.java
> +        QuizGame quizGame = new QuizGame();
QuizGame 클래스는 대부분 static으로 만들어져 있어서 new로 생성하는 게 맞지 않을 수도 있을 것 같습니다. 본래 의도라면 QuizGame의 메서드들의 static을 빼도 좋을 것 같습니다.

2023-09-18 08:49 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise02/Main.java
> +    public static int calculateDecimal(String hexString) {
parameter인, hexString 이라는 변수 이름을 참 잘 지으신 것 같아요! ㅎㅎ

2023-09-18 08:52 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise02/Main.java
> +            decimalNumber = decimalNumber * 16 + hexValue(hexString.charAt(i));
hexValue() 메서드에서 파라미터로 유효한 16진수 숫자 중 하나가 아니라면 -1을 반환하는데, 이를 처리하는 예외 처리 부분을 추가해주시면 더 좋을 것 같아요!! ㅎㅎ

2023-09-18 08:54 UTC, minsu11 reviewed
parkminsu review

2023-09-18 08:54 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise03/Main.java
> +        return random.nextInt(6) + 1;
Random class를 객체 생성 안하고 Math함수의 random을 사용하는 방안도 괜찮은 방법이 될거 같아요

2023-09-18 08:54 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise04/Main.java
> +        for (int i = 0; i < 10000; i++) {
반복문에서 10000을 하는 것 보다는 위에 전역변수로 값을 주는 것도 코드의 재사용성면에서 괜찮은 방식일거 같아요!

2023-09-18 08:54 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise04/Main.java
> +        while (dice() + dice() != goalValue) {
아니면 rollingNumber의 초기값을 1로 주는 것도 괜찮을 거 같습니다!

2023-09-18 08:54 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise06/RandomMosaicWalk2.java
> +    static void changeToRandomColor(int rowNum, int colNum) {
해당 메소드는 green을 변경하는 내용인데 changeToRandomColor보단 다른 이름이 더 좋을 것 같습니다!!

2023-09-18 08:54 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise08/QuizGame.java
> +    static int[] firstNum = new int[10];
앞에 private라고 작성하는 건 어떨까요? 그리고 생성자에서 new를 하는 방식이 더 좋은 거 같습니다!!

2023-09-18 08:54 UTC, minsu11 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise08/QuizGame.java
> +            firstNum[i] = random.nextInt(100);
범위를 100보다는 위에 변수 명으로 따로 값을 저장하시는 방식도 괜찮을 것 같습니다!!

2023-09-18 08:54 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise02/Main.java
> +                return character - '0';
1부터 9까지의 문자 값들을 숫자로 변환할 때, 완전 효율적으로 최적화를 잘 하신 것 같아요!

2023-09-18 10:06 UTC, 20203174 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise01/Main.java
> +        printCapitalized(userInput);
수정했습니다 ㅎㅎ

2023-09-18 10:40 UTC, 20203174 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise01/Main.java
> +                newString += Character.toUpperCase(checkSentence[i]);
헉 수정했습니다!

2023-09-18 10:44 UTC, 20203174 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise02/Main.java
> +            case 'A':
하하 수정했습니다

2023-09-18 10:57 UTC, 20203174 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise03/Main.java
> +            rollingNumber++;
😓수정했습니다!

2023-09-18 10:58 UTC, 20203174 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise03/Main.java
> +        System.out.println(diceRoll(scanner.nextInt()));
diceRoll에서 Exception을 던져주기 때문에 따로 처리하지 않았는데 scanner에서도 처리해줘야 할까요?
scanner.close() 수정했습니다!

2023-09-18 11:00 UTC, hyeonjaez reviewed
깔끔하게 잘 짜셨네요 굿굿

2023-09-18 11:00 UTC, hyeonjaez commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise02/Main.java
> +        Scanner scanner = new Scanner(System.in);
Scanner는 마지막에 close() 해주세요

2023-09-18 11:00 UTC, hyeonjaez commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise02/Main.java
> +                return 0;
다른 문자일때 0을 반환하기 보단 처음에 검증하는 로직이 필요 할거 같아요!!

2023-09-18 11:00 UTC, hyeonjaez commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise04/Main.java
> +        for (int i = 0; i < 10000; i++) {
이런 특정값은 전역변수로 final 상수로 설정해서 만들어 주면 좋을 거 같아요!

2023-09-18 11:00 UTC, hyeonjaez commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise05/Main.java
> +public class Main {
람다로 잘하셨네요 근데 모든 메서드에 final을 설정해준건 무슨 이유가 있을까요??

2023-09-18 11:00 UTC, hyeonjaez commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise08/Main.java
> +        QuizGame quizGame = new QuizGame();
좋은 설명인거 같습니다!!

2023-09-18 11:00 UTC, hyeonjaez commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise08/Main.java
> +            inputAnswer[i] = scanner.nextInt();
마지막에 scanner.close() 꼭! 해주세요!!!!!

2023-09-18 11:00 UTC, hyeonjaez commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise08/QuizGame.java
> +    public static String[] administerQuiz() { //퀴즈 목록 관리
메서드 이름 첫단어는 동사로 해주는게 좋아요

2023-09-18 11:01 UTC, 20203174 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise02/Main.java
> +            decimalNumber = decimalNumber * 16 + hexValue(hexString.charAt(i));
오 맞네요ㅠ 추가했습니다!

2023-09-18 11:09 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise06/RandomMosaicWalk2.java
> +    static void fillWithRandomColors() {
Mosaic.setColor() 메서드 에서 0, 0, 0을 활용해 검은색으로 전체를 채우는 메서드인 것 같아요! 그렇다면 fillWithBlackColor 과 같이 검정색이 표현되게 메서드 이름을 변경해주는 것은 어떨까요~?

2023-09-18 11:36 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise06/RandomMosaicWalk3.java
> +        switch (directionNum) {
case 문에서 중괄호 안에서 break 작성 안해도 괜찮은지 궁금합니다! case 뒤에 '->' 표시로 하면 자동으로 break가 걸리는 걸로 알고 있었는데, ':' 표시는 따로 break를 걸어주어야 하는가 싶어 코멘트 남깁니다...!

2023-09-18 11:42 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise08/QuizGame.java
> +    public static int[] getanswer() {
getAnswer() 이렇게 메서드 명을 대문자로 해주는 게 카멜 케이스로 더 좋을 것 같습니다 ㅎㅎ

2023-09-18 11:47 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise08/Main.java
> +        System.out.println("Quiz Start");
"Quiz Start" 출력해주는 부분이, 퀴즈 게임 생성자 내에서 호출되는 poseQuiz() 내에서 이뤄지면 본연의 의미를 살리는데 더 좋을 것 같습니다 ㅎㅎ

2023-09-18 11:51 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise08/QuizGame.java
> +    static int[] answer = new int[10];
문제에서 요구하는 세 번째 배열에는 user의 answer들이 있는 배열입니다! 따라서 배열 필드 이름을 userAnswers 라고 해보는 건  어떨까요~?

2023-09-18 11:53 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise08/QuizGame.java
> +    static int[] answer = new int[10];
그리고 세 개의 배열의 이름들에 s를 붙여서, firstNums, secondNums, userAnswers 라고  짓는다면 여러 개의 값이 들어가있다는 걸 더 잘 인식할 수 있을 것 같습니다~!

2023-09-18 11:55 UTC, prospro1 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise08/Main.java
> +        int[] inputAnswer = new int[10];
바로 이 부분에서 QuizGame 클래스의 필드를 활용하면 좋을 것 같습니다!

2023-09-18 12:02 UTC, prospro1 reviewed
yunhwa complete first code review

2023-09-19 08:01 UTC, 20203174 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise06/RandomMosaicWalk2.java
> +    static void fillWithRandomColors() {
좋은 의견입니다! 수정했습니다.

2023-09-19 08:04 UTC, nueag commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise06/RandomMosaicWalk3.java
> +        switch (directionNum) {
break; 써줘야 합니다ㅠㅠ 수정했습니다!

2023-09-19 08:10 UTC, 20203174 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise08/QuizGame.java
> +    static int[] answer = new int[10];
수정했습니다아!

2023-09-19 08:25 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise01/Main.java
> +        while(tmpSum != sumValue) {
tmpSum 변수 대신에 pariOfDice.getSumValue() 넣는 방식은 어떨까요??

2023-09-19 08:27 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise01/Main.java
> +        PairOfDice pairOfDice = new PairOfDice();
class constructor를 생성할 때 roll()메소드를 호출을 하는 부분이 있어서 loop문에서 roll 횟수를 측정할 때 1번 더 하게 되는거 같아요!! 생성자 부분의 roll메소드를 삭제하는건 어떨까요?

2023-09-19 08:31 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise03/Main.java
> +            System.out.printf("%.4f      \n", (int) statCalc.getMax());
실행했는데 18번째 줄에서 IllegalFormatConversionException 에러가 뜹니다!!

2023-09-19 08:35 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise04/BlackjackTest.java
> +            blackjackHand.addCard(deck.dealCard());
유저가 가진 카드들을 출력하는 부분을 추가하면 좋을 것같아요!

2023-09-19 08:37 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise07/Main.java
> +            @Override
AdditionQuestion class 형식처럼 private int a를 선언해줘서 random한 값으로 문제를 만드는 방식은 어떨까요??

2023-09-19 08:38 UTC, minsu11 reviewed
parkminsu code review

2023-09-19 08:39 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise05/BlackjackTest.java
> +        System.out.println("                      GAME START                      ");
\t을 사용하는 방식은 어떨까요??

2023-09-19 08:41 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise05/BlackjackTest.java
> +        dealer.addCard(deck.dealCard());
반복문을 사용해서 카드를 추가하는 방식도 괜찮을 것 같아요!!

2023-09-19 08:59 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise05/BlackjackHand.java
> +        System.out.println("===== " + getName() + " =====");
this를 써주는건 어떨까영?

2023-09-19 09:00 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise05/BlackjackHand.java
> +        for (int i = 1; i < blackjackHand.getCardCount(); i++) {
dealer는 한장만 보여주니깐 loop문을 사용안하고 바로 printf를 사용해도 괜찮을 것 같습니다!!

2023-09-19 09:04 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise05/BlackjackTest.java
> +    public static void main(String[] args) {
블랙잭 게임을 한번만 실행 하는 것이 아니라 여러 번 할 수 있게 하는 방식은 어떨까용??

2023-09-19 09:12 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise05/BlackjackTest.java
> +        if (dealer.whoIsWin() >= 0) return dealer.whoIsWin() == 0 ? false : true;
위의 조건문과 순서를 바꿔야할 것 같습니다!! 지금 방식은 유저와 딜러 둘 다 블랙잭일 경우 dealer가 아닌 user가 이기는 걸로 나올 것같습니다!!

2023-09-19 09:16 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise05/BlackjackTest.java
> +            if (userInput < 1 || userInput > 2) {
그럴 일은 없겠지만 혹시라도 문자열 또는 실수형 데이터가 들어왔을 경우를 예외처리하면 좋을 것같습니다!!

2023-09-19 09:21 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise05/BlackjackTest.java
> +                if (isAddDealer(dealer.getBlackjackValue())) {
해당 조건문을 메소드로 따로 만들어서 하는 방식은 어떨까요?? 밑에 같은 구조를 가진 조건문이 있어서 말씀드립니다!!

2023-09-19 09:22 UTC, minsu11 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise05/BlackjackTest.java
> +            if (userInput == 2) { //Stand
else if문을 사용하는 건 어떨까용?

2023-09-19 09:23 UTC, minsu11 reviewed
parkminsu code review

2023-09-19 09:27 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise01/Main.java
> +        PairOfDice pairOfDice = new PairOfDice();
동의합니다

2023-09-19 10:41 UTC, hyeonjaez reviewed
comment 했습니다

2023-09-19 10:41 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise04/BlackjackTest.java
> +        System.out.println("2~6개 중에 몇 개의 카드를 받으실 건가요?");
2부터 6까지 숫자가 아니면 예외처리 하는 로직을 구현 해야 할 거 같습니다

2023-09-19 10:41 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise05/BlackjackHand.java
> +    private int sumBlackjackValues;
사용하지 않은 변수는 삭제하는게 좋을 거 같아요!

2023-09-19 10:41 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise05/BlackjackTest.java
> +public class BlackjackTest {
블랙잭 게임을 진행하는 로직 같은데 BlackjackTest 라는 이름은 맞지 않은거 같아요!!

2023-09-19 10:41 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise05/BlackjackTest.java
> +        dealer.addCard(deck.dealCard());
동의합니다

2023-09-19 10:41 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise05/BlackjackTest.java
> +        if (dealer.whoIsWin() >= 0) return dealer.whoIsWin() == 0 ? false : true;
위에 로직이 둘중 하나가 블랙잭이면 이기는거 같은데 블랙잭 규칙이 딜러, 유저 둘다 블랙잭이면 딜러가 이기는 거라 순서를 바꾸면 좋을거 같습니다

2023-09-19 10:41 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise05/BlackjackTest.java
> +    public static boolean playBlackjackGame() {
전체적으로 이 메서드가 하는 행동이 많은 거 같아요 조금씩 메서드를 나눠주는게 어떨까요??

2023-09-19 10:41 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise07/Main.java
> +            if (scanner.nextInt() == intQ.getCorrectAnswer()) score += 10;
점수를 100점으로 정해놓고 한문제당 점수를 몇점씩 줄 것인지 구하는 로직이 있으면 좋을거 같아요

2023-09-19 10:41 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise07/Main.java
> +            public String getQuestion() {
뺄셈 문제를 만드는 class를 구현해보는건 어떨까요??

2023-09-19 10:41 UTC, hyeonjaez commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise07/Main.java
> +        intQuestions[QUIZ_NUM - 1] = new IntQuestion() {
곱셈 문제를 만드는 class를 구현해보면건 어떨까요??

2023-09-20 02:49 UTC, 20203174 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise01/Main.java
> +        PairOfDice pairOfDice = new PairOfDice();
맞네요! 수정했습니당

2023-09-20 02:50 UTC, 20203174 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise03/Main.java
> +            System.out.printf("%.4f      \n", (int) statCalc.getMax());
%.4f 때문에 에러가 난 것 같네요. 수정했습니당

2023-09-20 02:53 UTC, 20203174 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise04/BlackjackTest.java
> +            blackjackHand.addCard(deck.dealCard());
오 넵! 추가했습니다

2023-09-20 05:23 UTC, 20203174 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise01/Main.java
> +        while(tmpSum != sumValue) {
오! 감사합니당

2023-09-20 05:36 UTC, 20203174 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise05/BlackjackTest.java
> +        if (dealer.whoIsWin() >= 0) return dealer.whoIsWin() == 0 ? false : true;
예리한 지적이십니다 b

2023-09-20 06:09 UTC, 20203174 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise05/BlackjackTest.java
> +                if (isAddDealer(dealer.getBlackjackValue())) {
return값이 있어서 어려울 것 같은데... 좋은 방법이 있으시다면 알려주시면 감사하겠습니돠

2023-09-20 06:18 UTC, NANNDA3463 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise04/BlackjackTest.java
> +        Scanner scanner = new Scanner(System.in);
InputMismatchException과 같은 scanner 관련 exception 처리를 하면 좋을 것 같아요

2023-09-20 06:38 UTC, NANNDA3463 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise05/BlackjackTest.java
> +                if (isAddDealer(dealer.getBlackjackValue())) {
딜러가 이겼는지, 플레이어가 이겼는지에 대한 boolean 타입 필드를 만들면 될 것 같습니다.
그럼 메서드를 새로 만들고 리턴 타입을 void로 하고 if(dealer.whoIsWin() >= 0) 일 때는 위의 필드를 변경하는 식으로 하면 될 수도 있을 것 같아요

2023-09-20 06:40 UTC, NANNDA3463 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise07/Main.java
> +            @Override
문제에 랜덤한 값을 받았을 때, 정답이 음수가 되면 안된다는 지시사항이 있었던 점 참고해주세요

2023-09-20 06:41 UTC, NANNDA3463 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise07/Main.java
> +        Scanner scanner = new Scanner(System.in);
InputMismatchException 같은 scanner 관련 exception을 처리해주면 좋을 것 같습니다.

2023-09-20 06:51 UTC, NANNDA3463 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise05/BlackjackHand.java
> +    public void openCard(BlackjackHand blackjackHand) {
해당 매개변수가 dealer를 의미하는 것이라면, dealer라고 이름을 변경해주는 것이 좋을 것 같습니다.
 다만 한가지 의아한 점은, BlackjackHand의 의미는 플레이어의 손패를 의미하는데, 플레이어의 손패에 다른 사람의 패를 입력받아 처리하는 것이 조금 의아합니다. BlackjackHand를 사용하는 다른 클래스에서 이러한 메서드를 구현하거나, 아니면 자신의 패를 보여줄 수 있는 메서드로 변경하면 더 괜찮을 것 같습니다.

2023-09-20 07:01 UTC, NANNDA3463 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise05/BlackjackHand.java
> +        for (int i = 1; i < blackjackHand.getCardCount(); i++) {
반복문 i가 1부터 시작하기때문에 만약 첫 패에서 사용자가 stand를 하고, 딜러의 손패가 16보다 작을 경우, 카드 한장을 더 받게 되는데, 이 받은 패를 출력하지 않게 됩니다.
사용자는 stand를 하고 딜러가 카드를 뽑은 시점의 이후부터 딜러의 모든 카드를 볼 수 있어야 합니다.

해결 방법으론 openCard에서 딜러의 패는 첫번째 카드만 보여주면 되니, 인덱스로 접근하여 0번째 카드만 보여주게 하는 것도 방법 중 하나일 것 같습니다.
 다만 그렇게 만들면 프로그램의 흐름이 승패를 보여주고 카드를 공개하는데, 카드를 공개하고 승패를 보여주는 식으로 바꿔야겠습니다.

2023-09-20 07:02 UTC, NANNDA3463 requested changes
Gaeun 리뷰 했습니다

2023-09-21 00:42 UTC, NANNDA3463 commented on Chapter4/src/main/java/com/nhnacademy/gaeun/exercise03/Main.java
> +        System.out.println(diceRoll(scanner.nextInt()));
diceRoll에서 Exception을 던져줬다면 그 exception을 처리해주는 try-catch 부분이 있으면 더 완성도가 높을 것 같습니다.
예외로 둘의 Exception의 경우가 다른데, diceRoll에서 체크하는 exception은 parameter로 들어오는 값의 범위가 메소드의 의도와 다를 때 던지는 IllegalArgumentException이고,
 다른 하나는 scanner로 읽어들여야하는게 int가 들어와야하지만 사용자가 다른 데이터 타입(String, Double)을 입력 했을 때 나오는 InputMismatchException 입니다.
둘의 종류가 다르니 catch 해주면 좋을 것 같습니다

2023-09-21 01:08 UTC, prospro1 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise06/Main.java
> +            if (additionQuestion.getCorrectAnswer() == scanner.nextInt()) {
숫자 값이 아닌 값이 들어왔을 때, exception으로 던져주는 것보다 다시 적을 수 있는 기회를 주거나, 틀린 값으로 인식하는 것도 좋을 것 같다는 생각이 들었습니다! 저 또한 그렇게 코드를 고칠 예정입니다! 이건 원하시는 대로 하시면 될 것 같습니다!

2023-09-21 01:12 UTC, prospro1 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise07/Main.java
> +    private  static final double SCORE_UNIT = 100 / (ADD_QUIZ_NUM + MINUS_QUIZ_NUM + MULTIPLY_QUIZ_NUM);
100점 만점으로 설정하고 전체 문제 수로 나눠서 항상 100점이 만점으로 만드시는 거 너무 좋은 것 같습니다!!

2023-09-21 01:14 UTC, prospro1 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise07/MinusQuestion.java
> +        b = (int) (Math.random() * 50);
여기서 계산 결과값이 음수인 경우가 고려되지 않은 것 같습니다..! 처리해주시면 어떨까요~?

2023-09-21 01:16 UTC, prospro1 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise07/Main.java
> +        }
abstract class 로도 넣어보시는 거 추천드립니다! 문제에서 그렇게도 해보라고 제시되어 있어서 제안드립니다 :)

2023-09-21 01:16 UTC, prospro1 reviewed
yunhwa reviewed up to all the exercises of Chpater 5!

2023-09-21 01:52 UTC, 20203174 commented on Chapter5/src/main/java/com/nhnacademy/gaeun/exercise06/Main.java
> +            if (additionQuestion.getCorrectAnswer() == scanner.nextInt()) {
좋은 의견입니다! 수정했습니당

2023-09-22 02:07 UTC, minsu11 approved these changes
code approve

2023-09-22 02:08 UTC, hyeonjaez approved these changes
code approve

2023-09-22 02:10 UTC, NANNDA3463 approved these changes

2023-09-22 02:18 UTC, NANNDA3463 approved these changes

2023-09-22 02:29 UTC, merged